### PR TITLE
[14.0][MIG] base_ubl

### PR DESCRIPTION
**Pull request by rconjour**
Superseeding PR for https://github.com/OCA/edi/pull/303 by @phuctranerp

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! can you squash your feedback commit in the migration commit?

**Comment by rconjour** [comment]
> Thanks! can you squash your feedback commit in the migration commit?

Squashed the feedback commit.

**Review by StefanRijnhart — APPROVED** [review]

**Review by PieterPaulussen — APPROVED** [review]

**Review by dsolanki-initos — APPROVED** [review]
LGTM.

**Pull request merged**
