### PR TITLE
[14.0][MIG] account_invoice_import_invoice2data

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by bosd** [comment]
I'm happy to see this one come to V14. Will be happy to review once ready. :smile: 
Thanks a lot for all your effort Alexis :+1:

**Comment by bosd** [comment]
Does this one depend on the forward port of https://github.com/OCA/edi/pull/213

**Review by StefanRijnhart — APPROVED** [review]

**Review by rconjour — APPROVED** [review]
LGTM

**Comment by StefanRijnhart** [comment]
@bosd this is now green as indeed `account_invoice_import` was ported recently. Do you still want to review the (minor) changes?

**Comment by etobella** [comment]
There is a PR that adds a company field for 12.0. Can you check it and include here if you find it fine?
https://github.com/OCA/edi/pull/210

**Comment by StefanRijnhart** [comment]
@etobella it will be faster to merge this as is and then propose a new PR for the port of #210.

**Comment by etobella** [comment]
Well, it is a PR that has been waiting almost a year, so it will not be a problem to wait more time, but I think it is interesting enough. In any case, this is not blocking

**Comment by StefanRijnhart** [comment]
@etobella I already started reviewing that PR and the related PR, so I hope it will help moving it forwards.

**Comment by alexis-via** [comment]
@etobella This PR has been created 3 months ago... one year ago, v14 was not even released !!! :)

**Comment by etobella** [comment]
I know, don't worry @alexis-via :wink:

**Review by bosd — APPROVED** [review]
LGTM!

**Pull request merged**
