### PR TITLE
[15.0][DCK] Updated from template

### PR DESCRIPTION
**Pull request by victoralmau**
Updated from template

Ping @pedrobaeza 

@Tecnativa

### CODE REVIEW

**Comment by victoralmau** [comment]
@sergio-teruel can you check the error in tests? I do not know `edi_oca` module.

**Comment by etobella** [comment]
@victoralmau Can you try with this commit?
https://github.com/OCA/edi/commit/3fb967d95255e6e180268df4b183874ecef63f5a

I tested locally and it worked properly

Also, another error was raised but it is related to queue_job https://github.com/OCA/queue/pull/487

**Comment by victoralmau** [comment]
Thanks @etobella

**Comment by etobella** [comment]
There is still a warning raised https://github.com/OCA/edi/actions/runs/3593875771/jobs/6051404638#step:8:127

But it is dependent to the queue_job PR.

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
Fast tracking, as it might be necessary for other PRs 

/ocabot merge patch

**Pull request merged**
