### PR TITLE
[10.0][FIX] base_ubl: PartyName node is not mandatory in xsd so it should not be mandatory in code either.

### PR DESCRIPTION
**Pull request by SimoRubi**
I have edited one of the test files to allow testing this change, please advise me if I should test it in any other way.

### CODE REVIEW

**Comment by astirpe** [comment]
@SimoRubi I would prefer to keep that test unchanged.
Would be nice if you can create a new extra test for this specific case and perhaps checking that also other non-mandatory fields are correctly handled.
Anyway your PR looks good to me.

**Comment by SimoRubi** [comment]
Hi, thanks for the review!
I have created a separated file for tests as you suggested, and noticed this untested flow: https://github.com/OCA/edi/blob/046d68d1105144cb324325f0a45cd1dc240ccdef/sale_order_import/wizard/sale_order_import.py#L291-L305

So I have refactored a little the test class to allow testing this flow and ease adding future new tests.

**Comment by SimoRubi** [comment]
@OCA/edi-maintainers can someone take a look? Thanks

**Review by astirpe — APPROVED** [review]
Looks good! Thanks!

**Comment by SimoRubi** [comment]
@OCA/edi-maintainers can this be merged or should I change something? Thanks

**Review by tafaRU — APPROVED** [review]
LGTM Thanks!

**Review by SimoneVagile — APPROVED** [review]
Good for me, thanks!

**Comment by bealdav** [comment]
Please @astirpe maybe you can merge ?

**Pull request merged**
