### PR TITLE
[14.0][IMP] account_invoice_import: UI improvements

### PR DESCRIPTION
**Pull request by i-vyshnevska**

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by bosd — APPROVED** [review]
Quick code rev, lgtm

**Comment by i-vyshnevska** [comment]
@alexis-via can we proceed the merge here?

**Comment by bosd** [comment]
@dreispt  What needs to be fixed on this one??

**Comment by bosd** [comment]
@i-vyshnevska  Can you rebase?

**Comment by i-vyshnevska** [comment]
@bosd rebased

**Comment by bosd** [comment]
Jus tested functionally on runbot. LGTM.
@dreispt  Why is there a needs fixing label?
Can we get this one merged??

**Pull request merged**
