### PR TITLE
[15.0][FW] edi_oca: add exchange_filename search

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
FW of https://github.com/OCA/edi/pull/577

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
CC @LoisRForgeFlow @simahawk

**Review by etobella — APPROVED** [review]
LGTM But tests are failing

**Comment by bosd** [comment]
@etobella How can one solve the failling tests?? More PR's tests seems to be failling.
But it is caused by another module which is not even included in the pr.

```
2022-05-06 13:19:33,922 287 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.edi_account_oca.tests.test_edi.EDIBackendTestCase)
Traceback (most recent call last):
  File "/__w/edi/edi/edi_account_oca/tests/test_edi.py", line 18, in setUpClass
    super().setUpClass(chart_template_ref=chart_template_ref)
  File "/opt/odoo/addons/account/tests/common.py", line 31, in setUpClass
    assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
 
2022-05-06 13:19:34,209 287 INFO odoo odoo.modules.loading: Module edi_account_oca loaded in 0.99s (incl. 0.16s test), 135 queries (+2 test) 
2022-05-06 13:19:34,209 287 ERROR odoo odoo.modules.loading: Module edi_account_oca: 0 failures, 1 errors of 0 tests 

```

**Comment by etobella** [comment]
Well, is a collateral error raised by https://github.com/odoo/odoo/commit/15a1b3ae5cb1117e2c1bda5058d3cd99f00a6769

I will fix it in another PR

**Comment by etobella** [comment]
Fixed on #583 Can you rebase once it has been merged?

**Comment by JordiMForgeFlow** [comment]
Hi @etobella 

Thank you for the fix :) Rebase done!

CC @bosd

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Pull request merged**
