### PR TITLE
[13.0] edi: refactor component lookup

### PR DESCRIPTION
**Pull request by simahawk**
Depends on https://github.com/OCA/connector/pull/392

The match is now done based on specific control keys: backend type, exchange type.
This makes components more clean and their behavior more understandable.

@etobella this is what I was talking about last time :wink:

### CODE REVIEW

**Comment by simahawk** [comment]
@etobella can you review this and https://github.com/OCA/connector/pull/392 ?

**Review by etobella — APPROVED** [review]
The only thing I don't like is that old implementations will not work anymore with this changes. I have implemented one module (controlled, so no real problem) and I don't know if it will affect existent PRs

**Comment by simahawk** [comment]
> The only thing I don't like is that old implementations will not work anymore with this changes. I have implemented one module (controlled, so no real problem) and I don't know if it will affect existent PRs

well, if that's the case: override the usage candidates method and add them back where you need them.
If you have several implementation I can add backward support and log the deprecation.

**Comment by etobella** [comment]
Ok! @simahawk as soon as it is green, IMO we can proceed with merge :wink:

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
I restarted Travis, let's see if it becomes green now that the other PR has been merged.

**Comment by etobella** [comment]
@simahawk it seems related to the exchange_template

**Comment by etobella** [comment]
I made a PR on your branch fixing the test. I don't like the approach, but I didn't know a better option. Can you check it please?

**Comment by etobella** [comment]
@simahawk

**Comment by simahawk** [comment]
@etobella fixed in last commit in the right way :wink: 
Thanks for the reminder! :stuck_out_tongue:

**Comment by etobella** [comment]
I knew you will do it in the right way :stuck_out_tongue_closed_eyes: but this way you had an idea why the error was raised (And I was obviously saying it was a wrong approach :laughing: )

**Comment by simahawk** [comment]
> I knew you will do it in the right way stuck_out_tongue_closed_eyes but this way you had an idea why the error was raised (And I was obviously saying it was a wrong approach laughing )

jeje! Much appreciated :wink: Muchas gracias!

**Pull request merged**
