### PR TITLE
[FIX] can not change currency of existing company anymore

### PR DESCRIPTION
**Pull request by njeudy**
Fix failing test, because we can not change currency with company having existing data

### CODE REVIEW

**Comment by njeudy** [comment]
@astirpe here is failing test.

**Review by astirpe — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Instead of removing that part, please change currency by SQL

**Comment by njeudy** [comment]
@pedrobaeza why to try to change and test something that you could not do in Odoo ?

This part of code check that if you change company currency, the function still work .. but now on V11 you could not change company currency anymore .. 

I know I can use SQL but having only usefull tests is better ?

**Comment by pedrobaeza** [comment]
This is because we are testing a use case where the currency of the company is not the base one, and the same company is being used for not creating a company and all the related stuff (some kind of test shortcut). That's why I ask to keep it that way.

**Comment by njeudy** [comment]
@pedrobaeza travis hangs on : base_business_document_import/tests/test_business_document_import.py:107: [E8103(sql-injection), TestBaseBusinessDocumentImport.test_match_currency] SQL injection risk. Use parameters if you can. - More info https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#no-sql-injection

And I try with sql but I think I miss something .. can you help me ?

**Comment by njeudy** [comment]
@astirpe did you have some idea for this failing  test ?

**Comment by astirpe** [comment]
@njeudy can you try this?

```
cr.execute("UPDATE res_company SET currency_id = %s WHERE id = 1", (currency_id,))
```

**Comment by njeudy** [comment]
@astirpe nope .. that not correct .. think we are not in same env / cursor / transaction ... @pedrobaeza did you have an example for sql modification in tests ?

**Comment by astirpe** [comment]
@njeudy sorry, that line was meant for the sql-injection warning (that is now fixed).

About the failing test, isn't cursor `self.cr` working fine?
https://github.com/odoo/odoo/blob/11.0/addons/account/tests/test_reconciliation.py#L29

**Comment by njeudy** [comment]
@pedrobaeza @astirpe done :) and green / thanks for the help

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking this for having green branch.

**Pull request merged**
