### PR TITLE
[15.0][FIX] test_base_import_pdf_by_template: Improve pattern

### PR DESCRIPTION
**Pull request by victoralmau**
Backport from 17.0: https://github.com/OCA/edi/pull/1081

Improve pattern

Related to https://github.com/OCA/edi/pull/1071#issuecomment-2511881677

Related to pypdf 5.1.0 and line breaks

https://pypdf.readthedocs.io/en/latest/meta/CHANGELOG.html

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Same as v17.

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Ouch, CI is red.

**Comment by victoralmau** [comment]
The error is related to `account_invoice_facturx` but I don't know it and I don't know exactly how to solve it.

```
2024-12-03 13:15:12,935 368 ERROR odoo odoo.addons.account_invoice_facturx.tests.test_facturx_invoice: ERROR: TestFacturXInvoice.test_deep_customer_invoice
Traceback (most recent call last):
  File "/__w/edi/edi/account_invoice_facturx/models/account_move.py", line 873, in generate_facturx_xml
    xml_check_xsd(xml_byte, flavor="factur-x", level=ns["level"])
  File "/opt/odoo-venv/lib/python3.8/site-packages/facturx/facturx.py", line 172, in xml_check_xsd
    xsd_etree_obj = etree.parse(importlib.resources.files(__package__)
AttributeError: module 'importlib.resources' has no attribute 'files'
```

**Comment by pedrobaeza** [comment]
This sounds as a library version update with incompatible changes.

**Pull request merged**
