### PR TITLE
[MIG] edi_exchange_template_oca : Migration to 15.0

### PR DESCRIPTION
**Pull request by JuaniFreedoo**
Standard Migration @etobella

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Checked code

**Review by simahawk — CHANGES_REQUESTED** [review]
thanks for you contrib. Could you please rewrite the last commit?
Should be something like `[MIG] edi_exchange_template_oca : Migration to 15.0`

**Comment by JuaniFreedoo** [comment]
> 
Done, thanks for your help.

**Review by simahawk — APPROVED** [review]

**Pull request merged**
