### PR TITLE
[CHG] edi: Use more permissive licence: AGPL-> LGPL

### PR DESCRIPTION
**Pull request by etobella**
This change affects to
* base_edi
* edi
* edi_account
* edi_exchange_template
* edi_xml

It does not affect `edi_storage` as it's main module is AGPL.

@simahawk

### CODE REVIEW

**Comment by simahawk** [comment]
@sbidoul is this fine for you?

**Review by sbidoul — APPROVED** [review]
Yes. My opinion is that low level modules (base_rest, graphql, queue_job, edi framework etc) are best with a permissive license so we can use them with custom modules that depend on OE.

**Comment by simahawk** [comment]
@etobella regarding `edi_storage` let's ask @sebastienbeau @lmignon if we want to change license for storage base modules?

**Review by simahawk — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by lmignon — APPROVED** [review]
I also agree that we should also re licence `storage` addons to LGPL

**Comment by simahawk** [comment]
@etobella could you propose a change there too?

**Comment by etobella** [comment]
Sure!

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
