### PR TITLE
[13.0][FIX] edi_storage: incorrect call to output checker in receive component.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Checker is only relevant for output direction.

@ForgeFlow

### CODE REVIEW

**Review by etobella — APPROVED** [review]
I understand your approach. However, just to keep to be safe, a comment from @simahawk would be great to know if there was a reason for it

**Comment by LoisRForgeFlow** [comment]
> I understand your approach. However, just to keep to be safe, a comment from @simahawk would be great to know if there was a reason for it

I copied it from the output component, so it was my fault when creating this input component, Simone wouldn't have done such a mistake in the first place :stuck_out_tongue:

**Review by JordiMForgeFlow — APPROVED** [review]

**Comment by etobella** [comment]
https://github.com/OCA/edi/pull/402/files#diff-afd8f746cd5b16528b2bcead53330d7aa99b668b30305f51826902834179b3ddR17

I see, in that case it seem right to me to proceed with merge. Can you review that this error has not been added on 14?

/ocabot merge patch

**Comment by simahawk** [comment]
Hola! Seems I'm arriving late to the party :smile: 

> Simone wouldn't have done such a mistake in the first place stuck_out_tongue

Naaa it passed under my eyes in the 1st place... :wink: 

Indeed, doesn't make sense here, **today**.

TBH `check` is not really clear at all because it could be used for both input and output.
In the future we should maybe rename it to something more clear or pass the direction or something else.

**Comment by LoisRForgeFlow** [comment]
@etobella @simahawk travis issue fixed! could you merge?

**Pull request merged**
