### PR TITLE
[14.0] Misc fix/imp

### PR DESCRIPTION
**Pull request by simahawk**
Extrapolated from #451

### CODE REVIEW

**Comment by simahawk** [comment]
pre-commit error happening in many repositories:

```
 forbidden files......................................(no files to check)Skipped
Update pre-commit excluded addons........................................Passed
Fix the manifest website key.............................................Passed
autoflake................................................................Passed
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repobd80iqbs/py_env-python3/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/.cache/pre-commit/repobd80iqbs/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
    from typed_ast import ast3, ast27
  File "/home/runner/.cache/pre-commit/repobd80iqbs/py_env-python3/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /home/runner/.cache/pre-commit/repobd80iqbs/py_env-python3/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape

```

**Comment by sebalix** [comment]
@simahawk I got this error yesterday, I amended my last commit + force-push to get a new build and it was green. Don't know what is happening.

**Review by sebalix — APPROVED** [review]

**Comment by simahawk** [comment]
@sbidoul @Yajo have you seen this error before? https://github.com/OCA/edi/runs/4163605513?check_suite_focus=true#step:4:105

**Comment by sbidoul** [comment]
Not before today. The difference compared to the previous successful pre-commit run is the python version (3.9.8 vs 3.9.7). :cry:

**Comment by simahawk** [comment]
FTR pre-commit has been fixed here https://github.com/OCA/oca-addons-repo-template/pull/89 
I've just rebased.

**Review by TDu — APPROVED** [review]

**Pull request merged**
