### PR TITLE
[8.0][IMP] base_ubl_payment: Setting for default payment mode

### PR DESCRIPTION
**Pull request by thomaspaulb**
In some countries (Netherlands) the current default of 31 is invalid, so an option is given to change it.

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@astirpe For the final goal of having NLCIUS-consistent UBL's coming from Odoo 13.0, I'd need to get a couple of these 8.0 changes reviewed, then forward-port them to 13.0 as a whole bunch when they're deemed acceptable. Can I bother you with them? If someone with another country's perspective then steps in, he could make the final call.

**Comment by StefanRijnhart** [comment]
Looking at UBL specs for the first time. Do I understand correctly that NLCIUS recommends 30 (credit transfer) where 31 (debit transfer) is taken as the default in these OCA modules? Aren't these complete opposites?

**Comment by thomaspaulb** [comment]
@gjotten can you comment on this

**Comment by gjotten** [comment]
@StefanRijnhart & @thomaspaulb AFAICS the generic 30 and 31 payment means codes correspond with the new(er) additions '58 SEPA credit transfer' and '59 SEPA direct debit'. 

In other words, what we would consider an 'overboeking' vs. an 'incasso' in Dutch. But, 31 is neither automatic, direct, nor periodic and I believe it is on its way out or already unsupported in SEPA countries anyway.

Now NLCIUS supports 30, 58, and 59 as well as: 

- 48 (card payment)
- 49 (non-SEPA direct debit)
- 57 (standing agreement) 

I think we can safely say 48 is probably a PoS situation in the vast majority of cases, 49 is not relevant in SEPA countries, and 57 can be relevant but is kind of an outlier and best supported through a payment mode.

As for choosing a default, 30 as a generic option should be fine, but my choice would be 58.

**Comment by gjotten** [comment]
OTOH, since Odoo is used in non-SEPA countries as well I guess 30 would be the most logical default anyway.

**Comment by StefanRijnhart** [comment]
Thanks! I'm still slightly puzzled why the current default is a debit mode while you state that a credit mode makes more sense as a default (and support for direct debit in the current code is lacking (e.g. no mentioning of the mandate number)) but again, I'm very much overwhelmed reading bits and pieces of these specifications for the first time.

About covering the situation in which the payment mode is missing, I believe the vision of the original author is to ensure that the mode is present as much as possible, having provided modules us with modules such as 'account_payment_partner' and 'account_payment_sale'. Is there not a case to be made to deploy such modules rather than adding a global default payment mode *just for the UBL export of the invoice*?

**Comment by gjotten** [comment]
@StefanRijnhart without payment_mode_id being a required field on customer invoices, something has to set _a_ PaymentMeansCode in the .xml or UBL Business Rule 49 nets you a fatal error (i.e. the vendor's accounting software will most likely reject Odoo's invoice).

Account_payment_partner nets you nothing more than the chance to specify what it needs to be since payment mode is optional. So with the way it's set up now, a default is needed if you don't want users easily creating broken UBL data.

**Comment by StefanRijnhart** [comment]
OK. I'll abstain from further review because I don't have the required experience and my intuitions do not align with this change.

**Comment by thomaspaulb** [comment]
@StefanRijnhart Would your intuitions align better with a change that:

- Adds a related boolean field on invoice to check whether the invoice partner requires Dutch UBL (this field is computed on partner, by default when country = NL but you can override it)
- Uses this boolean to determine required=True or False for payment mode on invoice
- Adds a warning when you select a payment mode that has no UNECE code defined

**Pull request closed without merging**
