### PR TITLE
[15.0][MIG] edi_voxel_account_invoice_oca: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36455

ping @carlosdauden @victoralmau 

depends on:
- [x] https://github.com/OCA/edi/pull/676
- [x] https://github.com/OCA/stock-logistics-workflow/pull/1147

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Comment by victoralmau** [comment]
`edi_voxel_oca` is merged now. Could you rebase to check tests?

**Comment by sergio-teruel** [comment]
Rebase done!

**Comment by victoralmau** [comment]
> Rebase done!

Ok, thanks. I see that it is still necessary to merge https://github.com/OCA/stock-logistics-workflow/pull/1147 (`stock_picking_invoice_link`)

**Comment by sergio-teruel** [comment]
Rebase done!!

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
