### PR TITLE
[8.0] IMP base_ubl: set a base_company_view

### PR DESCRIPTION
**Pull request by bealdav**
Settings UI for v8 only

cc @alexis-via 

Note: 10+ have settings standard page

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]
ok, why not.
As said in comment, this is only for v8 ; higer versions use config pages and have "account_e-invoice_generate" for a common base between UBL and FX

**Comment by bealdav** [comment]
**Runbot result**

----------
Module test summary
('\x1b[1;32mSuccess\x1b[0;m', 'account_invoice_import,account_invoice_import_invoice2data,account_invoice_import_ubl,account_invoice_import_zugferd,account_invoice_ubl,account_invoice_zugferd,base_business_document_import,base_business_document_import_phone,base_business_document_import_stock,base_ubl,base_ubl_payment,base_zugferd,purchase_order_import,purchase_order_import_ubl,purchase_order_ubl,sale_commercial_partner,sale_order_import,sale_order_import_csv,sale_order_import_ubl,sale_order_ubl,sale_stock_order_import')

+=======================================
|  Tests summary:
|---------------------------------------
| test_server.py              [1;32mSuccess[0;m
+=======================================
 * Stopping PostgreSQL 9.6 database server       [80G 
[74G[ OK ]

----

**Travis**

+=======================================
|  Tests summary:
|--------------------------------------
| test_server.py              Success
+=======================================

The command "travis_run_tests" exited with 0.
cache.2

store build cache

after_success

4.25s$ travis_after_tests_success

Done. Your build exited with 0.
========

Mergeable I presume @alexis-via

**Comment by bealdav** [comment]
Please @astirpe could you review it ? Thanks

**Review by astirpe — APPROVED** [review]

**Pull request merged**
