### PR TITLE
[12.0][MIG] account_invoice_ubl_email_attachment

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Comment by mgielissen** [comment]
Merge?

**Comment by astirpe** [comment]
@mgielissen did you test this V12 module?

**Comment by mgielissen** [comment]
Yes, I'm using it already.

**Comment by astirpe** [comment]
@mgielissen ok, thanks! Would you please go to "Files changed" -> "Review changes", and then "Approve"?

**Review by mgielissen — APPROVED** [review]

**Pull request closed without merging**
