### PR TITLE
[14.0][MIG] account_invoice_ubl_email_attachment

### PR DESCRIPTION
**Pull request by bobslee**
Same code is PR https://github.com/OCA/edi/pull/463

### CODE REVIEW

**Comment by bosd** [comment]
:) please fix pre-commit

**Comment by bobslee** [comment]
@bosd Some action needed by me ?

**Comment by bosd** [comment]
Not really, but you could always leave a review at the other pr :) 
The other PR is basically your code. But I followed the OCA migration procedure. Fixed pre-commit.

Was struggling a bit with the commits. That's the reason your not mentioned as an author. Hope you don't mind.

**Comment by bobslee** [comment]
@bosd Thanks for responding. Ok all good :)

**Comment by bosd** [comment]
@bobslee 🍻🍻 please review

**Comment by bobslee** [comment]
@bosd Code has been reviewed and tested https://github.com/OCA/edi/pull/463

How can we trigger a rebuild, to see the pre-commit error ?
I don't have experience with GitHub actions yet.

**Comment by bosd** [comment]
@bobslee  I have fixed the pre-commit issue and made a new pr in #631 .
I told you, that I was struggeling with git commands, somehow the commits you've made are now attributed to me.
Luckly, you are ok with that, so I would propose we would merge that version. Then this pr can be closed.


> How can we trigger a rebuild, to see the pre-commit error ?
I don't have experience with GitHub actions yet.

You can push an empty commit to retrigger the actions: https://www.freecodecamp.org/news/how-to-push-an-empty-commit-with-git/

**Pull request closed without merging**
