### PR TITLE
[15.0][MIG] edi_voxel_stock_picking > edi_voxel_stock_picking_oca: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36459

ping @carlosdauden @CarlosRoca13 

Depends on:
- [x] https://github.com/OCA/edi/pull/676

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Comment by sergio-teruel** [comment]
Rebase done!!

**Comment by ernestotejeda** [comment]
@sergio-teruel associate channels with delayable methods via XML. See https://github.com/OCA/edi/pull/714

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
