### PR TITLE
[16.0][PORT] 826 from 14.0

### PR DESCRIPTION
**Pull request by bosd**
Port #826 from 14.0 to 16.0.

### CODE REVIEW

**Review by Dranyel-Bosd — APPROVED** [review]
Functionally review

**Review by bofiltd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@simahawk Can you please merge this one?? :pray:

**Comment by bosd** [comment]
@alexis-via Can you please merge :pray:

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
