### PR TITLE
[14.0][MIG] edi_voxel: Migration to 14.0

### PR DESCRIPTION
**Pull request by AntoniRomera**
Standard Migration with module rename

### CODE REVIEW

**Comment by AntoniRomera** [comment]
@etobella I did something wrong for the pre-commit to fail, I don't understand why it still points to the old name.

**Comment by olgamarcocb** [comment]
Good morning,

In order to change a module name, I would create a new branch and then execute this command:

git filter-branch -f --index-filter '
git ls-files --stage | \
sed "s:**old_name**/:**new_name**/:" | \
GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
git update-index --index-info && \
mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"
' HEAD

Replacing **old_name** by edi_voxel and **new_name** by edi_voxel_oca

**Comment by pedrobaeza** [comment]
Do you think the renaming is needed? I doubt Odoo is going to implement a `edi_voxel` module. Anyways, if renamed, you have to rewrite full story with:

```
git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD
```

**Comment by AntoniRomera** [comment]
> Do you think the renaming is needed? I doubt Odoo is going to implement a `edi_voxel` module. Anyways, if renamed, you have to rewrite full story with:
> 
> ```
> git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD
> ```

The name change is to maintain coherence with the rest of the modules.

**Comment by pedrobaeza** [comment]
OK, then perform the whole history re-writing.

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Comment by AntoniRomera** [comment]
@pedrobaeza I don't understand what happened, can you help me?

**Comment by pedrobaeza** [comment]
It seems the history is totally unrelated and it got closed. After performing the command I put, you have to do a rebase over 14.0. Try that, forced push and the reopen, or open a new PR.

**Comment by AntoniRomera** [comment]
> It seems the history is totally unrelated and it got closed. After performing the command I put, you have to do a rebase over 14.0. Try that, forced push and the reopen, or open a new PR.

github doesn't allow me to do the PR as the commit history is totally different, I think I'll do the migrate without the name change or see if someone knows how to do it. 

@olgamarcocb @pedrobaeza

**Comment by pedrobaeza** [comment]
As said, you have to rewrite the history and then do the rebase. You are missing the final rebase according your comments.

**Pull request closed without merging**
