### PR TITLE
[IMP] edi: archive edi_backend

### PR DESCRIPTION
**Pull request by JaumeBforgeFlow**
Adding the feature to archive edi.backend so they can be ignored on searches.

### CODE REVIEW

**Comment by etobella** [comment]
Can you add the ribbon on the form view?

**Comment by JaumeBforgeFlow** [comment]
Done

**Comment by etobella** [comment]
Squash the commits on a single one please :wink:

**Review by etobella — APPROVED** [review]
LGTM 

Tested on runboat

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
