### PR TITLE
[17.0][FIX] pdf_helper: Odoo compatibility

### PR DESCRIPTION
**Pull request by victoralmau**
Odoo compatibility

Related to https://github.com/odoo/odoo/pull/183165

@Tecnativa

### CODE REVIEW

**Comment by victoralmau** [comment]
I'm not sure of the proper solution, if you install `pypdf` it seems that's when the error happens. any suggestions?

**Comment by pedrobaeza** [comment]
@simahawk do you have any clue?

**Comment by simahawk** [comment]
maybe this? https://github.com/OCA/edi/pull/1041

**Comment by victoralmau** [comment]
> maybe this? #1041

Thanks, but that doesn't seem to solve the problem https://github.com/OCA/edi/actions/runs/11520562675/job/32072176936?pr=1057#step:8:56.

**Comment by pedrobaeza** [comment]
I have finally disabled the test for now, as we need to greenify the branch.

FWIW, it seems Odoo wrapping class is calling `add_metadata` super method without first initializing empty metadata, provoking the assert.

/ocabot merge patch

**Pull request merged**
