### PR TITLE
[12.0][MIG] account_invoice_import_ubl

### PR DESCRIPTION
**Pull request by astirpe**
Depends on:

- [x] https://github.com/OCA/edi/pull/162

### CODE REVIEW

**Comment by mgielissen** [comment]
Any progess?

**Comment by mgielissen** [comment]
With the latest version I can import UBL XML files.

**Review by jgrandguillaume — APPROVED** [review]
LGTM

**Review by desdelinux — APPROVED** [review]
functional review is ok

**Pull request merged**
