### PR TITLE
[14.0][MIG] base_facturx

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by fshah-initos** [comment]
Hi @alexis-via is it possible to fix the failed checks?

**Review by fshah-initos — APPROVED** [review]
Code review . No major change.

**Comment by fshah-initos** [comment]
Hi @all It would be great if someone could add  review to this PR.

**Comment by alexis-via** [comment]
FYI, I'll probably do large changes in this module to implement Order-X (I started to work on it, but I'm busy on other OCA modules at the moment). But this can also happen in a later PR.

**Comment by fshah-initos** [comment]
Can we merge this PR?

**Comment by fshah-initos** [comment]
Is it possible to merge the PR ?

**Review by sebastienbeau — APPROVED** [review]

**Pull request merged**
