### PR TITLE
[15.0][FWD] edi_oca: port changes from 14.0

### PR DESCRIPTION
**Pull request by simahawk**
Changes from #470, #519, #579, #549, #524, #614, #634, #640, #643, #645

To be merged w/ `nobump`

### CODE REVIEW

**Comment by simahawk** [comment]
@victoralmau there you go. As per comments on #640 can you do some manual testing?

**Comment by victoralmau** [comment]
> @victoralmau there you go. As per comments on #640 can you do some manual testing?

Sorry, I don't know the module well enough to do manual testing, I was only able to do a code review to help.

**Comment by simahawk** [comment]
> > @victoralmau there you go. As per comments on #640 can you do some manual testing?
> 
> Sorry, I don't know the module well enough to do manual testing, 

You asked for the port of #640 I thought you could do it :wink: 
Ok, let's see who can help.

> I was only able to do a code review to help.

Good, thanks.

**Review by MiquelRForgeFlow — APPROVED** [review]
We need this merged ASAP.

**Comment by MiquelRForgeFlow** [comment]
@simahawk This branch has conflicts, please resolve them

**Comment by simahawk** [comment]
@MiquelRForgeFlow pls check again, I rebased but I have no time to check deeply.

**Comment by MiquelRForgeFlow** [comment]
@simahawk LGTM

**Comment by simahawk** [comment]
Rebased again after #717 

/ocabot merge minor

**Pull request merged**
