### PR TITLE
[14.0] Misc boost tests 

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM

**Review by bofiltd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
Oops we merged this..

But overlooked this error..
image

**Comment by simahawk** [comment]
I think there's something crazy in the TestCase suite of Odoo core: it does not detect import errors as errors in the tests...

**Comment by simahawk** [comment]
voilá https://github.com/OCA/edi/pull/883

**Comment by bosd** [comment]
> I think there's something crazy in the TestCase suite of Odoo core: it does not detect import errors as errors in the tests...

Indeed, seems something to do with test suite..
Also for cases like this https://github.com/OCA/server-ux/pull/779/files

Migration script appearantly does not cover. Tests pass even with these errors.
Should we discuss this somewehere? Maintainer repo?

**Pull request merged**
