### PR TITLE
[10.0][FIX]fix kwarg in message_post

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
This PR is green for 6 weeks now.
Please merge.

**Review by BenjaHe — APPROVED** [review]
Approved

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]
A classic one!

**Comment by pedrobaeza** [comment]
@luc-demeyer it seems there's a problem in Travis when rebasing. Can you please check?

**Comment by luc-demeyer** [comment]
all checks have passed hence imho you can merge this fix.

**Comment by jgrandguillaume** [comment]
@luc-demeyer It still seems broken, can you check it again ?

**Pull request closed without merging**
