### PR TITLE
[UPD] base_wamas_ubl: Update grammars ART, ARTEAN, WEAK, WEAP, related tests and fix utils

### PR DESCRIPTION
**Pull request by tuantrantg**
* Edit ART grammar and fix parsing boolean value to string
* Update grammars of ARTEAN, WEAK, WEAP and related tests

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@tuantrantg as per [#913 ](https://github.com/OCA/edi/pull/913#issuecomment-1916782549) pls, try to keep commit msg clear

**Comment by tuantrantg** [comment]
> @tuantrantg as per [#913 ](https://github.com/OCA/edi/pull/913#issuecomment-1916782549) pls, try to keep commit msg clear

Hi @simahawk please review it again, thank you

**Comment by simahawk** [comment]
to be rebased

**Comment by tuantrantg** [comment]
> to be rebased

hi @simahawk it's rebased

**Pull request merged**
