### PR TITLE
8.0 FIX two stupid bugs

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Maybe you can change the commit message to follow the convention ([FIX] account_invoice_import: ...) and to avoid non pleasant words.

**Comment by Doscaal** [comment]
:+1:

**Review by YannisPV — APPROVED** [review]

**Review by yvaucher — APPROVED** [review]

**Comment by alexis-via** [comment]
@pedrobaeza These are my bugs, so I'm unpleasant with myself. I promise, I'll do better commit messages next time... and you will teach me how to change a commit message afterwards (I'm don't have a git-fu badge like Sylvain G.)

**Comment by yvaucher** [comment]
@alexis-via the git-fu kata to learn to change commit message is:

```
git commit --amend
# rename it in editor then :wq (if vi)
git commit push --force
```

and you are done :wink:

**Pull request merged**
