### PR TITLE
[13.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by sbidoul**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by yvaucher** [comment]
I think this one is addressed here #213 

base_business_document_import/models/business_document_import.py:83:5: C901 'BusinessDocumentImport._match_partner' is too complex (25)

With commit:

https://github.com/OCA/edi/pull/213/commits/fc6116f6e8f2b72c1ed1d900e3c99e97306b6d74


Which I can extract in a separate PR

**Comment by simahawk** [comment]
Funny thing: the complex method check is disabled on that method and locally I don't get the error. 
@yvaucher can I cherry-pick your commit or it requires changes from the rest of your PR?

**Comment by simahawk** [comment]
well, let's try :D

**Pull request merged**
