### PR TITLE
[14.0][IMP] account_invoice_import: fwd ports for ATI Support (tests)

### PR DESCRIPTION
**Pull request by bosd**
Forward porting the tests for ATI support.
ATI Support depends on: #826 

One of commits needed to support ATI as mentioned in #293

### CODE REVIEW

**Comment by bosd** [comment]
@Dranyel-Bosd Can you please review?

**Review by Dranyel-Bosd — APPROVED** [review]
Look so good to me

**Comment by bosd** [comment]
@etobella, @simahawk Can you please review?

**Review by etobella — APPROVED** [review]
Makes sense to me

/ocabot merge patch

**Pull request merged**
