### PR TITLE
[ADD] new addon to automatically import invoice from files in server directories

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
This PR add an automatic process to upload file from directories and feed the wizard in account_invoice_import addon.

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@alexis-via What is your opinion on this PR ?

**Comment by alexis-via** [comment]
Seems funny :) I'm afraid you caught the same virus as me on electronic invoicing and accounting automation... 

I guess that this module tries to be a solution to avoid manually dropping the PDF in Odoo ; copying to a directory of Odoo (shared by Samba to the accounting team of the company) is certainly easier. Is that your goal when developping this module ? Another approach would be to have a daemon that listen to new files in that directory (via inotify) and, when it finds a new PDF or XML file, immediately sends it to Odoo's account invoice import wizard. That would avoid the need to wait for the scheduler to run ; you would get the result in Odoo immediately.

**Comment by Cedric-Pigeon** [comment]
@alexis-via The goal of this is to receive ubl files from another platform which do the OCR job (https://www.arco.be/en/).

**Comment by alexis-via** [comment]
FYI, I proposed another approach than this module: a script that use inotify to auto-push invoices to Odoo. Advantage: no need to wait for the cron to run, the invoices is sent to Odoo immediately after save. https://github.com/OCA/edi/pull/84

**Pull request closed without merging**
