### PR TITLE
[14.0] Add lines management to create multiline invoices

### PR DESCRIPTION
**Pull request by MTantin**
Multiline invoice creation is not supported yet.

I propose those modifications to accept multiline creation.

Invoice2data library accept format (with parser or not) to extract invoice line by line with regex.
the result is stored in "lines" field as json list.
I iterate over this list to prepare data for account_invoice_import submodule.

### CODE REVIEW

**Comment by bosd** [comment]
Thanks for this PR. We're working on the same functionality.
See PR: https://github.com/OCA/edi/pull/573
However, mine does not include tests. Bu thas more doc's and fields.
Would you like to contribute your code to that pr? Or leave a review?

**Comment by bosd** [comment]
Oops, made the same comment on your previous PR.
Why did you open a new one?

**Comment by bosd** [comment]
Import is failling as there is no known template found for Gandi.
Can you share your template file?

**Comment by MTantin** [comment]
> 
Here is our template for Gandi's invoices

```
# -*- coding: utf-8 -*-
issuer: Gandi
fields:
  amount: Total \(EUR\)\s+(-?\d+,?\.?\d+)
  amount_untaxed: Sous-total\s+(-?\d+,?\.?\d+)
  date: Facture\s+n\°\s+(\d{8})
  invoice_number: Facture\s+n\°\s+(\d+)
  vat: TVA ([a-zA-Z]{2}\d+)
  partner_name: Gandi
  siren: SIRET\s+(\d{3}\s*\d{3}\s*\d{3})
  lines:
    parser: lines
    start: Produit\s+Description\s+Propriétaire\s+Taxes\s+Prix
    end: Répartition
    line: (?P<name>.+)\s{2,}(?P<taxes>\d+)%\s{2,}(?P<price_unit>-?\d+,\d+)\s+€
    types:
      price_unit: float
      taxes: float
keywords:
  - Gandi SAS
  - SIRET 423 093 459 00042
options:
  currency: EUR
  date_formats:
      - '%Y%m%d'
  languages:
    - fr
  decimal_separator: ','
```

**Pull request closed without merging**
