### PR TITLE
[14.0][MIG] base_business_document_import

### PR DESCRIPTION
**Pull request by alexis-via**
This PR is an improvement of PR #301 with additionnal tests and improvement in error handling. The migration of account_invoice_import is based on it.

### CODE REVIEW

**Comment by rconjour** [comment]
@alexis-via can you rebase against https://github.com/OCA/edi/pull/301 because the merge conflict is resolved there.

**Review by rconjour — APPROVED** [review]
LGTM, however, i prefer to use the `default-paramater` on `dict.get`, but the `or` also does the trick!

**Comment by StefanRijnhart** [comment]
Can we agree to merge #301 as is and then immediately merge this one afterwards? I think your work falls under 'improvements' so we can merge it separately from the migration PR and give credits where credits are due.

**Comment by alexis-via** [comment]
@StefanRijnhart I kept the commits of @phuctranerp without changes.

**Comment by StefanRijnhart** [comment]
Yes, I know that! So we can merge that PR first without any impact, right?

**Comment by alexis-via** [comment]
yes, sure, we can do that. Merging this one directly would make the same result. Both scenarios are OK.

**Comment by StefanRijnhart** [comment]
Oh, I did not expect that a rebase would be necessary but it is.

**Comment by alexis-via** [comment]
OK, I'll try to find time to work on this in the coming days. I also need to finish the PR for account_invoice_import ; I'm almost ready.

**Comment by rconjour** [comment]
@alexis-via i'll create a superseding PR for this, so you can continue on account_invoice_import

**Comment by rconjour** [comment]
Created superseding PR: https://github.com/OCA/edi/pull/366/commits

**Comment by StefanRijnhart** [comment]
Green on the superseding PR. Closing here

**Pull request closed without merging**
