### PR TITLE
[15.0][MIG] edi_voxel_sale_secondary_unit: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36457

ping @carlosdauden @CarlosRoca13 

Depends on:
- [x] https://github.com/OCA/edi/pull/676
- [x] https://github.com/OCA/edi/pull/678

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]
Migration code review

**Comment by sergio-teruel** [comment]
ping

**Comment by CarlosRoca13** [comment]
It LGTM please reopen to set the review :smile:

**Comment by pedrobaeza** [comment]
GitHub is not allowing me to reopen. I'm proposing another PR.

**Pull request closed without merging**
