### PR TITLE
[13.0][MIG] account_invoice_ubl_email_attachment

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by yvaucher — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]

**Comment by CasVissers-360ERP** [comment]
Functional review.

**Comment by CasVissers-360ERP** [comment]
Can be merged?

**Comment by mgielissen** [comment]
Any plans for migrating to 14.0?

**Comment by CasVissers-360ERP** [comment]
@mgielissen 
We will be migrating it soon. Planned for this or next week.

**Pull request merged**
