### PR TITLE
[16.0][IMP] sale_order_import: Improve sale_order_import to warn user…

### PR DESCRIPTION
**Pull request by lethuthao2403**

### CODE REVIEW

**Comment by santostelmo** [comment]
@lethuthao2403  The code LG
Is possible to write a small test asserting that the exception is raised ?

**Review by simahawk — COMMENTED** [review]
LG but I agree on the test.
BTW any reason to keep it in draft?

**Comment by simahawk** [comment]
commit msg could be rewritten 

`[IMP] sale_order_import: warn user when no price is defined in the file`

No odoo version and no need to repeat the module name :wink:

**Comment by lethuthao2403** [comment]
The PR has been updated. Thank you!

**Review by cyrilmanuel — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@lethuthao2403 can you check the build?

**Comment by lethuthao2403** [comment]
The PR has been updated. Thank you!

**Review by cyrilmanuel — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Pull request merged**
