### PR TITLE
[14.0][MIG] account_invoice_download

### PR DESCRIPTION
**Pull request by alexis-via**
Requires PR #394 

I already ported account_invoice_download_ovh ; i still need to clean it up and then I'll create the PR.

### CODE REVIEW

**Review by davejames — APPROVED** [review]
works well for me as part of testing #397

**Review by njeudy — APPROVED** [review]
Ok with my tests

**Comment by davejames** [comment]
@alexis-via I guess this would pass now if you rebased it considering https://github.com/OCA/edi/pull/394 has been merged?

**Comment by alexis-via** [comment]
Travis is green. Let's merge

**Pull request merged**
