### PR TITLE
[ADD] Adjust the facturx embedded format in account_invoice_facturx

### PR DESCRIPTION
**Pull request by ikapasi-initos**

### CODE REVIEW

**Comment by ikapasi-initos** [comment]
Hi @alexis-via  it would be great if you can add reviews here.

**Review by dsolanki-initos — APPROVED** [review]
Code review and Functional test, LGTM!

**Comment by jans23** [comment]
@alexis-via I think this is a useful fix, at least we need it to avoid errors. Can you reopen the PR, please?

**Comment by bosd** [comment]
can you fix pre-commit?

**Comment by jans23** [comment]
@bosd pre-commit is fixed now.

**Review by bosd — APPROVED** [review]
very quick code review. 👍

**Comment by bosd** [comment]
@alexis-via Can this be merged?

**Comment by bosd** [comment]
@oca/edi-maintainers This carries the approved label. Can it get merged?

**Pull request closed without merging**
