### PR TITLE
[14.0][MIG] account_invoice_ubl: Migration to 14.0

### PR DESCRIPTION
**Pull request by hailangvn**
This PR is to replace https://github.com/OCA/edi/pull/330 due to no response from owner after several pings.

### CODE REVIEW

**Comment by simahawk** [comment]
@hailangvn tests log is taking too long. Can you apply the same approach taken here https://github.com/OCA/edi/pull/468 by muting useless logging?

**Comment by simahawk** [comment]
Note that I fwd ported an improvement from 13.0 here https://github.com/camptocamp/edi/commit/c3e707d25096e45ae60776c9787c940c29f932ae could you cherry-pick it? (reported on https://github.com/OCA/edi/pull/477)

**Comment by hailangvn** [comment]
> Note that I fwd ported an improvement from 13.0 here [camptocamp@c3e707d](https://github.com/camptocamp/edi/commit/c3e707d25096e45ae60776c9787c940c29f932ae) could you cherry-pick it? (reported on #477)

Thanks @simahawk for the comment. I thought that the `[13.0][IMP] account_invoice_ubl & base_ubl: add hooks` in this PR history has that change. I cherry-picked it anyway.

**Comment by hailangvn** [comment]
From nils@trobz.com: When generating the report, wkhtmltopdf creates 2 requests in parallel to get assets which creates 2 threads that are stuck because of a lock on new registry. That is why `HttpSavepointCase` is being used for `TestUblInvoice` class.

**Comment by simahawk** [comment]
> From [nils@trobz.com](mailto:nils@trobz.com): When generating the report, wkhtmltopdf creates 2 requests in parallel to get assets which creates 2 threads that are stuck because of a lock on new registry. That is why `HttpSavepointCase` is being used for `TestUblInvoice` class.

Ahh, I see... Would you mind adding a comment before the class declaration?

@sebalix could we benefit from what you have done in our project to pre-load assets?

**Comment by nilshamerlinck** [comment]
Some notes about the `HttpSavepointCase` choice:
- by default, when running in a test, [`_render_qweb_pdf` falls back on `_render_qweb_html`](https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/ir_actions_report.py#L736)
- but in `*_ubl` modules, we explicitly [`force_report_rendering`](https://github.com/OCA/edi/blob/13.0/account_invoice_ubl/models/account_move.py#L90)
- as such, wkhtmltopdf runs and when rendering the report content, creates 2 requests to retrieve assets (`web.report_assets_common.css`, `web.report_assets_pdf.css`)
- but when the test is running, there is a [lock on the registry](https://github.com/odoo/odoo/blob/14.0/odoo/modules/registry.py#L37) because the module is being installed
- so the 2 assets requests are stuck in threaded mode, [waiting for the lock to be released](https://github.com/odoo/odoo/blob/14.0/odoo/modules/registry.py#L61)
- 2 workarounds:
  - here: use `HttpCase` or `HttpSavepointCase` classes that [disable the lock](https://github.com/odoo/odoo/blob/14.0/odoo/modules/registry.py#L684)
  - or change tests to `@tagged('-at_install', 'post_install')` (run after installation is complete)

**Comment by simahawk** [comment]
> Some notes about the `HttpSavepointCase` choice:
> 
>     * by default, when running in a test, [`_render_qweb_pdf` falls back on `_render_qweb_html`](https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/models/ir_actions_report.py#L736)
> 
>     * but in `*_ubl` modules, we explicitly [`force_report_rendering`](https://github.com/OCA/edi/blob/13.0/account_invoice_ubl/models/account_move.py#L90)
> 
>     * as such, wkhtmltopdf runs and when rendering the report content, creates 2 requests to retrieve assets (`web.report_assets_common.css`, `web.report_assets_pdf.css`)
> 
>     * but when the test is running, there is a [lock on the registry](https://github.com/odoo/odoo/blob/14.0/odoo/modules/registry.py#L37) because the module is being installed
> 
>     * so the 2 assets requests are stuck in threaded mode, [waiting for the lock to be released](https://github.com/odoo/odoo/blob/14.0/odoo/modules/registry.py#L61)
> 
>     * 2 workarounds:
>       
>       * here: use `HttpCase` or `HttpSavepointCase` classes that [disable the lock](https://github.com/odoo/odoo/blob/14.0/odoo/modules/registry.py#L684)
>       * or change tests to `@tagged('-at_install', 'post_install')` (run after installation is complete)

Thanks for the details @nilshamerlinck !
I'd go for the last option and run tests at post_install only.
I let you decide tho :wink:

**Review by simahawk — APPROVED** [review]
LG

**Review by TDu — APPROVED** [review]

**Pull request merged**
