### PR TITLE
12.0 account invoice import out invoices

### PR DESCRIPTION
**Pull request by cesarlr**
Adds a wizard to import Out Invoices and fixes some searches to allow partner_id as Customer instead of Supplier. Also fixes the view used in this new case.

### CODE REVIEW

**Comment by cesarlr** [comment]
@rvalyi @ovnicraft @pniederlag @cmayo Can you review?

**Comment by ovnicraft** [comment]
@cesarlr please add some screen shot with changes in wizard.

**Comment by cesarlr** [comment]
imagen

**Comment by cesarlr** [comment]
imagen

**Comment by cesarlr** [comment]
imagen

**Comment by cesarlr** [comment]
imagen

**Comment by cesarlr** [comment]
> @cesarlr please add some screen shot with changes in wizard.

Here they are!

**Comment by cesarlr** [comment]
Hi! The CI pipeline is green again

**Comment by cesarlr** [comment]
@alexis-via @etobella @bealdav Can you review?

**Comment by etobella** [comment]
The button import from file is not present in customer invoices, is this right?

**Comment by cesarlr** [comment]
> The button import from file is not present in customer invoices, is this right?

Sorry, I don't know what button you mean

**Comment by cesarlr** [comment]
Hi @etobella can you explain your last comment, please?

**Comment by bosd** [comment]
Can you trigger the build of a runboat??
E.g. force push?

**Pull request closed without merging**
