### PR TITLE
[15.0][MIG] edi_voxel_oca: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36454

ping   @CarlosRoca13 @carlosdauden

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why is it red?

**Comment by sergio-teruel** [comment]
This module has not tests. The tests are in the other modules that extend the mixin

**Comment by pedrobaeza** [comment]
@etobella @simahawk do you know about this error in `edi_oca`?

https://github.com/OCA/edi/actions/runs/3496333620/jobs/5854123764#step:8:140

**Comment by victoralmau** [comment]
CI fixed with https://github.com/OCA/edi/pull/683

**Pull request merged**
