### PR TITLE
[14.0][MIG] edi_xml (and renamed to edi_xml_oca)

### PR DESCRIPTION
**Pull request by simahawk**
Collateral change for `edi_oca` in this commit:  

[edi_oca: add more generic mixin](https://github.com/OCA/edi/commit/399ba39b0efb49ec16e23bdef8dd65b1af7dce7f)

edi_oca version already bumped so that we can merge w/ nobump

### CODE REVIEW

**Comment by simahawk** [comment]
/ocabot migration edi_xml_oca

reopened mig issue

**Comment by bosd** [comment]
Very quick code review, lgtm.

**Pull request merged**
