### PR TITLE
[14.0][MIG] edi_backend_partner

### PR DESCRIPTION
**Pull request by FerranCforgeFlow**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@simahawk should this be renamed to `edi_backend_partner_oca` in v14?

**Comment by etobella** [comment]
It has sense to rename it

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by RaulOForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Pull request merged**
