### PR TITLE
[16.0][MIG] base_ubl_payment

### PR DESCRIPTION
**Pull request by jbaudoux**
Includes:
* https://github.com/OCA/edi/pull/861

I added the invoice `payment_reference` as default `PaymentID` instead `None`

### CODE REVIEW

**Review by bofiltd — APPROVED** [review]
LGTM

**Review by bosd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@etobella Can you please have a look at this pr? Is it ok to merge?

**Review by rousseldenis — APPROVED** [review]
LGTM.

Even if I think adding tests should be great

**Comment by rousseldenis** [comment]
@OCA/accounting-maintainers

**Comment by grindtildeath** [comment]
@rousseldenis the right team would be @OCA/edi-maintainers :wink:

**Comment by rousseldenis** [comment]
> @rousseldenis the right team would be @OCA/edi-maintainers 😉

Indeed :sweat_smile:

**Pull request merged**
