### PR TITLE
[14.0][IMP] base_ubl: add hooks to allow customization

### PR DESCRIPTION
**Pull request by FerranCforgeFlow**
Return the _item_ node in the __ubl_add_item_ method of the base_ubl

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

**Review by bealdav — APPROVED** [review]

**Comment by etobella** [comment]
Wouldn't be easier to apply the same changes from here:
https://github.com/OCA/edi/pull/429/files

This way, this hooks are no longer necessary

**Comment by LoisRForgeFlow** [comment]
@etobella Probably you are right and that will be the best solution going forward. However, since these hooks are already in v13, I find some benefit in just including them in v14 as they are now and keeping versions aligned. Less migration headaches! :smile:

**Comment by etobella** [comment]
I know it is easier, but it is the best place to do this on migrations, so, I would prefer to add a return and remove the need of this hooks

**Comment by LoisRForgeFlow** [comment]
@etobella OK, let's do that then. 

@FerranCforgeFlow Could you attend Enric's suggestion?

**Comment by FerranCforgeFlow** [comment]
Done! All the changes related with the supplier party have been removed since in #429 the node is returned and can be edited, and the item node of the __ubl_add_item_ method is now also returned.

**Review by etobella — APPROVED** [review]

**Pull request merged**
