### PR TITLE
[14.0] mig account_invoice ubl_email_attachment

### PR DESCRIPTION
**Pull request by bosd**
Continuation of https://github.com/OCA/edi/pull/531

### CODE REVIEW

**Comment by bosd** [comment]
@simahawk 🙏 Can you retrigger tests?

**Review by astirpe — APPROVED** [review]

**Comment by bosd** [comment]
@simahawk Can you review?

**Comment by bosd** [comment]
@bobslee Propably still had some 🍻  in my system last week.
As I asked you to review #531 , but actually I wanted to ask you to review this one.
This one is superseding and fixes the pre-commit issue.

Can you review this one?

**Comment by bobslee** [comment]
@bosd Ofcourse I can imagine the :beers: got you hooked.

I just compared your PR (code) with my commit, the one from my PR #531
The commit: https://github.com/bobslee/edi/commit/5533949f33bb5f781d353ec50a1eb2559c2455ab

I don't think your PR is correct, especially the code in the `models/mail_template.py` will be errornous.
Did you ran the unit tests ? I didn't ran the tests from your PR tough.

I recommend you to arrange the PR #531, I don't have much time this week to settle this.
Thanks! :smiley:

**Comment by bosd** [comment]
> I don't think your PR is correct, especially the code in the `models/mail_template.py` will be errornous.

Can you specifically comment, what should be changed, in a review here.
(Please comment/review on a line level)

> Did you ran the unit tests ? I didn't ran the tests from your PR tough.

Tests are ok here on github ci.

> I recommend you to arrange the PR https://github.com/OCA/edi/pull/531, I don't have much time this week to settle this.

I don't have write acces to your repo. But I can incorporate changes in this pr.
Just let me know, what you want to have changed.

If I'm not mistaken, this version (same as in 531) is already used in production for a client.

**Comment by bobslee** [comment]
Just copy/paste from my PR and check the diff.
Sorry I'm too busy now and already proposed my PR a while ago.

It was also tested (by Mario Gielissen and Cas Vissers if I'm correct)

**Review by bofiltd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@etobella Can this one be merged? 🙏

**Pull request merged**
