### PR TITLE
[15.0][MIG] base_business_document_import

### PR DESCRIPTION
**Pull request by pcastelovigo**
As requested in #466

Module works, hopefully I'll make it pass the requirements

### CODE REVIEW

**Comment by pcastelovigo** [comment]
@simahawk I'm reading plan is to deprecate this... Could you give me directions? I would like to clone from OCA but a repository of my own is acceptable

**Comment by simahawk** [comment]
> @simahawk I'm reading plan is to deprecate this... Could you give me directions? I would like to clone from OCA but a repository of my own is acceptable

Where are you reading this? 
The module is already available on v16 https://github.com/OCA/edi/tree/16.0/base_business_document_import hence I doubt we'll deprecate or do major refactoring before v17 or even 18

**Comment by etobella** [comment]
I think you are not maintaining Commit history

**Comment by bosd** [comment]
Maybe better to base the work upon: https://github.com/OCA/edi/pull/737

**Comment by pcastelovigo** [comment]
> Maybe better to base the work upon: #737

I have a test-passing clone on a repo, but it doesnt pass codecov

**Pull request closed without merging**
