### PR TITLE
[14.0][MIG] edi_voxel > edi_voxel_oca

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Now the renaming seems OK :)

You can check the CIs

**Comment by AntoniRomera** [comment]
@olgamarcocb @etobella

**Comment by AntoniRomera** [comment]
@olgamarcocb Looks good to you?

**Review by etobella — APPROVED** [review]

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Comment by AntoniRomera** [comment]
@etobella Can it be merged and the rest of the voxel modules can be migrated?

**Comment by pedrobaeza** [comment]
I think that these modules should be now adapted to OCA EDI infrastructure for better integration and lesser code.

**Comment by AntoniRomera** [comment]
> I think that these modules should be now adapted to OCA EDI infrastructure for better integration and lesser code.

I don't have enough experience with components to make the change of structure.

**Comment by AntoniRomera** [comment]
If someone can explain it to me, I can take care of it.

**Comment by pedrobaeza** [comment]
@etobella can you help on this? I haven't dug enough yet on the EDI framework

**Comment by etobella** [comment]
Sure! @AntoniRomera I tried to contact you using Discord in order to have a meeting.

**Pull request merged**
