### PR TITLE
FIX too recent invoice2data versions causes Odoo crash

### PR DESCRIPTION
**Pull request by flotho**
FIX https://github.com/OCA/edi/issues/445

### CODE REVIEW

**Comment by flotho** [comment]
ping @alexis-via

**Comment by alexis-via** [comment]
@flotho is it because invoice2data dropped py2 support ?

**Comment by flotho** [comment]
> @flotho is it because invoice2data dropped py2 support ?

I didn't check but probably yes.
Regards

**Review by etobella — APPROVED** [review]
Is no longer compatible with python2.7, so it seems logic

**Comment by flotho** [comment]
thanks @etobella

**Pull request merged**
