### PR TITLE
[15.0][MIG] edi_voxel_stock_picking_secondary_unit: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36460

ping @carlosdauden @victoralmau 

Depends on:
- [x] https://github.com/OCA/edi/pull/681
- [x] https://github.com/OCA/edi/pull/679

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by carlosdauden — APPROVED** [review]
Code LGTM

**Pull request merged**
