### PR TITLE
[12.0] edi_oca: Fix Access error for Administrator (backport)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Backport of https://github.com/OCA/edi/pull/974.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Can someone merge it?

**Comment by MiquelRForgeFlow** [comment]
ping: @etobella @simahawk

**Comment by MiquelRForgeFlow** [comment]
Can we merge this, please?

**Review by etobella — APPROVED** [review]

**Review by MateuGForgeFlow — APPROVED** [review]

**Pull request merged**
