### PR TITLE
[16.0][MIG] base_edi: Migration to 16.0

### PR DESCRIPTION
**Pull request by john-herholz-dt**
Migration of base_edi module. I will be migrating other modules also.

Note: This is my first github contribution ever, so if anything that is missing, please let me know.

### CODE REVIEW

**Review by flotho — APPROVED** [review]
code review
LGTM

**Comment by etobella** [comment]
Can you rename last commit with the proper name `[MIG] base_edi: Migration to 16.0` ?

**Comment by john-herholz-dt** [comment]
@etobella I did the rebase, thanks for the hint. All in all nothing special here, just a version bump since no actual code in this module.

**Review by etobella — APPROVED** [review]
LGTM

**Pull request merged**
