### PR TITLE
remove option --test-report-directory

### PR DESCRIPTION
**Pull request by joshuajan**

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why do you need to remove it?

**Comment by joshuajan** [comment]
Hello @pedrobaeza  

Because this option is not use in V12

**Comment by pedrobaeza** [comment]
Any way it's harmless...

**Comment by joshuajan** [comment]
Hello @pedrobaeza . 
Yes, but it seems will make the CI test failed.

**Comment by astirpe** [comment]
Indeed travis fails with error:

```
odoo-bin: error: no such option: --test-report-directory
```

Please merge this PR as soon as possible.

**Comment by pedrobaeza** [comment]
OK, then it's harmless. Merging.

**Pull request merged**
