### PR TITLE
[17.0]MIG] base_business_document_import: Migration to 17.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Ref: BSRD-752

Depend on:

- [ ] https://github.com/OCA/community-data-files/pull/181
- [ ] https://github.com/OCA/community-data-files/pull/192

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@nguyenminhchien base_unece was migrated and merged in https://github.com/OCA/community-data-files/pull/193 and https://github.com/OCA/community-data-files/pull/192 is merged -> can you update the unreleased dependencies?

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien base_unece was migrated and merged in [OCA/community-data-files#193](https://github.com/OCA/community-data-files/pull/193) and [OCA/community-data-files#192](https://github.com/OCA/community-data-files/pull/192) is merged -> can you update the unreleased dependencies?

Updated.

**Pull request merged**
