### PR TITLE
[IMP]base_ubl_payment: Add payment means to SEPA direct debit/credit …

### PR DESCRIPTION
**Pull request by bosd**
…transfer

Fixes:

image
When creating a peppol invoice.

Screenshot from:
https://test.peppolautoriteit.nl/validate

By adding:
image

### CODE REVIEW

**Review by Dranyel-Bosd — APPROVED** [review]
looks so good to me :+1:

**Review by bofiltd — APPROVED** [review]
Code review, Makes sense :laughing:

**Comment by bosd** [comment]
@oca/maintainers, can we get a merge? :pray:

**Comment by bosd** [comment]
@alexis-via Is this one ok to you?

**Comment by bosd** [comment]
@etobella Can you please merge 🙏

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Comment by bosd** [comment]
@etobella Is the oca bot sleeping?? 🤖 ?

**Pull request merged**
