### PR TITLE
[FIX] remove pin version of dateparser

### PR DESCRIPTION
**Pull request by florian-dacosta**
Issue reported here https://github.com/OCA/edi/issues/544 is fixed in recent version of dateparser.
Fixed here I believe : https://github.com/scrapinghub/dateparser/issues/1045

### CODE REVIEW

**Comment by florian-dacosta** [comment]
@simahawk

**Comment by simahawk** [comment]
shall we pin `dateparser >= $minor_version_with_the_fix`?

**Review by bosd — APPROVED** [review]
Please fasttrack this. As the module is not installable due to a version conflict!

**Comment by bosd** [comment]
> shall we pin dateparser >= $minor_version_with_the_fix

LGTM

**Review by rvalyi — APPROVED** [review]

**Comment by bosd** [comment]
@florian-dacosta @rvalyi Can you attend to this?

**Comment by bosd** [comment]
Why does it fail?

**Comment by rvalyi** [comment]
@bosd @florian-dacosta the merge failed because dateparser was still pinned to the old version in `edi_pdf2data_oca/__manifest__.py` so the requirements.txt generation would still pick the pinned version and be different than it was in the PR.
I fixed that in a fixup! commit.

Still OK with the PR?

**Comment by bosd** [comment]
Yes, please proceed

**Pull request merged**
