### PR TITLE
.travis.yml: Fix it with new template

### PR DESCRIPTION
**Pull request by astirpe**
Backport of #118. Cherry-picked from a2671fa.
Also add MAKEPOT.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Same problem about PG 9.6

**Comment by astirpe** [comment]
Now Travis fails for the following error:

```
The XML file is invalid against the XML Schema Definition
XSD Error: Element '{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}TypeCode': [facet 'enumeration'] The value '31' is not an element of the set {'10', '20', '30', '42', '48', '49', '57', '58', '59', '97', 'ZZZ'}., line 44
No valid XML file found in the PDF
FAIL

```


I think I need help for this, as we don't use factur-x.

**Comment by pedrobaeza** [comment]
The real problem is the `assert` you have changed:
```
2019-07-25 12:56:16,048 5824 ERROR openerp_test odoo.addons.account_invoice_factur-x.tests.test_facturx_invoice: ` AssertionError: None != 'factur-x.xml'
```
https://travis-ci.org/OCA/edi/jobs/563533926#L1198

**Comment by astirpe** [comment]
Before that change on the `assert`, this was the error:

```
2019-07-25 12:13:07,990 5726 ERROR openerp_test odoo.addons.account_invoice_factur-x.tests.test_facturx_invoice: ` AssertionError: None is not true : factur-x.xml
```

https://travis-ci.org/OCA/edi/jobs/563522056#L1198

**Comment by pedrobaeza** [comment]
Well, then the problem seems to be that it should be something, not `None`. @alexis-via please check the problem.

**Comment by astirpe** [comment]
@pedrobaeza Even if this PR ends in red, the travis failure is caused by just one test of module account_invoice_factur-x and not by the travis config.
Still this PR improves the situation: it fixes the error that is actually blocking all the PRs on branch 10.0 (see for example https://travis-ci.org/OCA/edi/builds/554320657?utm_source=github_status&utm_medium=notification). You can notice that the error is preventing every test and lint check to be executed; this PR is a fix for this.

I would ask to merge it as it is, so that the pending PRs can be rebased.
Also consider that PRs #118 and #119 were already merged and this one is just a backport.

**Comment by pedrobaeza** [comment]
Then put the test as it was, or we will have a red Travis.

**Comment by astirpe** [comment]
@pedrobaeza done.

**Comment by pedrobaeza** [comment]
Uhm, but Travis is still failing... so we don't get the green status we need. I can merge it, but we will still have the same red status for the rebased PRs. @alexis-via can you please check the problem?

**Comment by astirpe** [comment]
@pedrobaeza that's what I was trying to say in https://github.com/OCA/edi/pull/120#issuecomment-516723233. Even the this PR will not make the travis green, at least it will allow travis to run the tests.

**Comment by pedrobaeza** [comment]
I would bet for commenting that line for now.

**Pull request merged**
