### PR TITLE
[FIX] travis

### PR DESCRIPTION
**Pull request by etobella**
Disables execution on travis of modules that are not working properly due to PR #208 

This is obviously a patch for other modules on the repo to work properly. It is obviously needed to solve the original issue

### CODE REVIEW

**Comment by bealdav** [comment]
Hi @etobella maybe you might be inspired with that

https://github.com/OCA/l10n-france/blob/12.0/.travis.yml#L32

to exclude only the module in conflict instead of exclude many modules

**Comment by etobella** [comment]
This pr is just a patch. Also, i would have to remove all the modules on the exclude as all depend on the uninstallable module. Not removing one if them would rise an error. Also, this way codecov is saying that is untested.

At the end an exclude from a base autoinstalled module is not great IMO. And that is something that should be fixed by the author

**Comment by etobella** [comment]
At the end, I followed your comments. When this is green, it would be interesting to merge it soon

**Comment by bealdav** [comment]
Yeah, you're pragmatic @etobella , really nice

**Review by bealdav — APPROVED** [review]

**Review by simahawk — APPROVED** [review]
let's patch it!

**Pull request merged**
