### PR TITLE
[17.0][FW][IMP] base_edi: introduce a basic edi user group

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
FW of https://github.com/OCA/edi/pull/1004

### CODE REVIEW

**Review by SilvioC2C — APPROVED** [review]

**Comment by SilvioC2C** [comment]
@JordiMForgeFlow PR LGTM but tests are failing

**Comment by JordiMForgeFlow** [comment]
@victoralmau do you know why the test for _test_base_import_pdf_by_template_ may be giving a wrong result?

**Comment by simahawk** [comment]
I'm trying to trigger the build on 17.0, let's see, but it could also be a flappy test.

**Comment by simahawk** [comment]
well the build here is green https://github.com/OCA/edi/pull/1056 :D

**Comment by JordiMForgeFlow** [comment]
@simahawk they are modifying the module in that PR, so maybe those changes are needed in order to greenify this one.

**Comment by simahawk** [comment]
MAybe https://github.com/OCA/edi/pull/1080 :)

**Comment by victoralmau** [comment]
Already solved with https://github.com/OCA/edi/pull/1081

**Comment by JordiMForgeFlow** [comment]
thank you @victoralmau :)

**Pull request merged**
