### PR TITLE
[10.0][FIX] Model name error in _match_journal()

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by astirpe — APPROVED** [review]
Please bump module version

**Comment by pedrobaeza** [comment]
Travis and runbot are red

**Comment by astirpe** [comment]
Just opened https://github.com/OCA/edi/pull/87 to check if it fixes the travis+runbot issue

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by astirpe** [comment]
Rebased

**Pull request merged**
