### PR TITLE
[IMP] account_invoice_import_invoice2data: Allow a field for company vat

### PR DESCRIPTION
**Pull request by etobella**
This will integrate with #205

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]

**Review by albariera — APPROVED** [review]

**Comment by etobella** [comment]
@alexis-via I would prefer to get your review before the merge please :smile:

**Review by StefanRijnhart — APPROVED** [review]

**Comment by etobella** [comment]
@hhgabelgaard I took your commits in order to fix it.

I will merge as soon as it is green

#415

**Comment by etobella** [comment]
#403 This fixes the branch too (the original commit has another goal, but it is already approved)

**Pull request merged**
