### PR TITLE
[FIX] edi_oca: Missing changes of name

### PR DESCRIPTION
**Pull request by etobella**
Some errors where found during the migration of related modules. For this reason #372 is failing

@fshah-initos

### CODE REVIEW

**Comment by etobella** [comment]
I have tested the tests on #372 and worked properly, also a JS error was raised, now it is fixed (the widget would not appear...)

**Review by simahawk — APPROVED** [review]
seems more than legit :smile: 
Any other find/replace loop missing? :stuck_out_tongue_winking_eye:

**Comment by etobella** [comment]
I hope there isn't more :laughing:

**Pull request merged**
