### PR TITLE
[12.0] account_invoice_import_simple_pdf (invoice2data alternative)

### PR DESCRIPTION
**Pull request by alexis-via**
This is a backport from v14 to v12 of the PR https://github.com/OCA/edi/pull/420

### CODE REVIEW

**Review by mourad-ehm — APPROVED** [review]
Test in prod.

**Comment by alexis-via** [comment]
OK, I think that the travis red by is caused by the fact the the tests run on python 3.5... whereas PyMuPDF only supports Python 3.6 and above, cf https://pypi.org/project/PyMuPDF/
The tests for v14 run on python 3.6 and there are no errors when installing PyMuPDF/fitz.
I made a test push with python 3.6 just to see if it fixes travis.

**Comment by alexis-via** [comment]
OK, the cause of the pb was not the one in my last comment. I think I now get it, let's see if Travis is green this time.

**Comment by olaf-wagner** [comment]
I'd like to test it but seem unable to install the module after merging the PR branch locally. I've got this environment:
```
odoo@cfab0e0c607f:/$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
odoo@cfab0e0c607f:/$ python3 --version
Python 3.7.3
```
Just installing pymupdf via pip3 does not work. I've tried to install these dependencies I was able to recognize:
```
   38  sudo apt-get install mupdf
   40  sudo apt-get install mupdf-dev
   42  sudo apt-get install libmupdf-dev
   47  sudo apt-get install libfreetype6-dev
```
After that I get thousands of C compilation errors (will only show the first):
```
odoo@cfab0e0c607f:/$ sudo pip3 install PyMuPDF
Collecting PyMuPDF
  Using cached https://files.pythonhosted.org/packages/62/cf/13e7c886d2f6cfcbed78962278f9f3843126f5f8cc30f0baa9eb524f44bd/PyMuPDF-1.19.1.tar.gz
Building wheels for collected packages: PyMuPDF
  Running setup.py bdist_wheel for PyMuPDF ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ul70q62s/PyMuPDF/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-hqwi9uh4 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/fitz
  copying fitz/__init__.py -> build/lib.linux-x86_64-3.7/fitz
  copying fitz/fitz.py -> build/lib.linux-x86_64-3.7/fitz
  copying fitz/utils.py -> build/lib.linux-x86_64-3.7/fitz
  copying fitz/__main__.py -> build/lib.linux-x86_64-3.7/fitz
  running build_ext
  building 'fitz._fitz' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/fitz
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/usr/include/freetype2 -I/usr/include/python3.7m -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.7/fitz/fitz_wrap.o
  fitz/fitz_wrap.c:2779:5: error: conflicting types for ‘fz_pixmap_size’
   int fz_pixmap_size(fz_context *ctx, fz_pixmap *src);
       ^~~~~~~~~~~~~~
...
```
What are the exact dependencies to install on a Debian 10 system?
What am I missing?
Any help appreciated.
If this is the wrong location for this discussion I will happily take it elsewhere and delete this comment.

**Comment by vdewulf** [comment]
@alexis-via Hi Alexis, hope you're well!
I'd like to test this awesome module in v12. Is it testable in current state? I can't really understand from this thread.
Thanks a lot!

**Comment by alexis-via** [comment]
Hello @vdewulf 
It works well. We use it in production in v12 for our own use at Akretion and we like it a lot !

**Comment by vdewulf** [comment]
@alexis-via oh that's great, we'll take this PR with our Gitaggregator and test it as well.
Thanks!

**Comment by carmenbianca** [comment]
@alexis-via The declared version `PyMuPDF==1.9.2` is somehow not installable through pip:

```bash
$ pip install PyMuPDF==1.9.2
ERROR: Could not find a version that satisfies the requirement PyMuPDF==1.9.2 (from versions: 1.11.2, 1.12.5, 1.13.20, 1.14.19.post2, 1.14.19.2, 1.14.20, 1.14.21, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.16.7, 1.16.8, 1.16.9, 1.16.10, 1.16.11, 1.16.12, 1.16.13, 1.16.14, 1.16.15, 1.16.16, 1.16.17, 1.16.18, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.17.6, 1.17.7, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.18.6, 1.18.7, 1.18.8, 1.18.9, 1.18.10, 1.18.11, 1.18.12, 1.18.13, 1.18.14, 1.18.15, 1.18.16, 1.18.17, 1.18.18, 1.18.19, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.19.6, 1.20.0rc1, 1.20.0rc3, 1.20.0, 1.20.1)
ERROR: No matching distribution found for PyMuPDF==1.9.2
```

I do not know _why_.

We've been using version 1.16.18 of PyMuPDF in prod.

**Comment by carmenbianca** [comment]
@alexis-via pr is stale. I bump.

**Pull request closed without merging**
