### PR TITLE
[15.0][IMP] base_edi: introduce a basic edi user group (Backport from 16.0)

### PR DESCRIPTION
**Pull request by QuocDuong1306**
A suggestion from the author (of the module) @simahawk 
- https://github.com/OCA/edi/pull/1004#issuecomment-2219596625

### CODE REVIEW

**Comment by pedrobaeza** [comment]
`[BKP]` doesn't exit as tag, as why not cherry-picking the commit from 16.0? You are removing the attribution.

**Comment by QuocDuong1306** [comment]
Hi @pedrobaeza , I have a suggestion from @simahawk ([here](https://github.com/OCA/edi/pull/1004#issuecomment-2219596625))

Btw, in many repositories, I saw a `[BKP]` tag is used for this case (Backport), Did I miss sth, could you suggest it?

**Comment by pedrobaeza** [comment]
OK about the attribution. I thought it was from other author. It's good that you link the original pull request for avoiding these misunderstandings.

About the commit message, it's not correct although some use them: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by QuocDuong1306** [comment]
This commit was merged on 16.0. Do we need to change the commit message? If yes, which message do you suggest for this one (It will be helpful for me to contribute to OCA at the other times also)

**Comment by pedrobaeza** [comment]
I think the only problem is to put `[BKP]` in the PR title. The commit message already contains `[IMP]`.

**Review by simahawk — APPROVED** [review]

**Pull request merged**
