### PR TITLE
[15.0][MIG] base_business_document_import

### PR DESCRIPTION
**Pull request by hhgabelgaard**
Std. migrations

Depends on:
- [x] #736

### CODE REVIEW

**Comment by bosd** [comment]
Are you still working on this?

**Comment by hhgabelgaard** [comment]
No, but I think it is ready for review.
But we are not using it any more. Fell free to take over.

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM👍🎆

**Comment by bosd** [comment]
Can you please include:
052498102c98117aceec1ed32f30f1f8714aed9c
db864b0a6607710875091444a31f6a2a3eb1fc96
f168b48c9aaf5f2c838005a2524d185a70a89659

**Comment by bosd** [comment]
hmm, in hindsight, maybe better to start a new migration..

**Pull request closed without merging**
