### PR TITLE
[17.0][FIX] test_base_import_pdf_by_template: Improve pattern

### PR DESCRIPTION
**Pull request by victoralmau**
Improve pattern

Related to https://github.com/OCA/edi/pull/1071#issuecomment-2511881677

Related to pypdf 5.1.0 and line breaks

https://pypdf.readthedocs.io/en/latest/meta/CHANGELOG.html

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by pedrobaeza** [comment]
Is this needed for v16? Should we pin the pypdf library version?

**Comment by victoralmau** [comment]
> Is this needed for v16? Should we pin the pypdf library version?

The module does not exist in v16, only in v15.

**Comment by pedrobaeza** [comment]
Well, I meant if it was needed for previous versions.

**Comment by simahawk** [comment]
@victoralmau can you please check https://github.com/OCA/edi/issues/1088 ? Thanks!

**Pull request merged**
