### PR TITLE
[WIP][8.0] Merge EDI incubator

### PR DESCRIPTION
**Pull request by adrienpeiffer**
By @alexis-via 

From OCA/account-invoicing#122
From OCA/sale-workflow#332
From OCA/purchase-workflow#267

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe it's possible to reduce a bit the number of commits squashing some of them together?

**Comment by alexis-via** [comment]
:+1: Great ! Travis is green. Thank you VERY MUCH to @adrienpeiffer for the hard work with git/travis/...

**Comment by rousseldenis** [comment]
:+1: Great work @alexis-via!

**Comment by gva-acsone** [comment]
👍 (functional test)

**Comment by luanaduarte** [comment]
👍 Functional test

**Comment by alexis-via** [comment]
We have a problem: this branch doesn't contain the changes I made this morning: commit 2f319c2a74bd6ae39f8d5e51f7cdf8348ba78385:

Add support for extraction + matching on website

```
Add mimetype text/xml in addition to application/xml
FIX issue in account_invoice_import_invoice2data
```

So it seems that someone made a push -f on the branch.
And the commit of @houssine78 is not pep8 compliant (this change was already included in my commit of this morning but pep8 compliant)

**Comment by alexis-via** [comment]
OK, I remember now: before going for lunch, I tried to push my commit but it failed with an error "ERROR: Sorry, but @edi-sprint has blocked access to SSH keys created by some third-party applications. Your key was created before GitHub tracked keys created by applications, so we need your help." and I forgot to investigate the issue after lunch. So I pushed again my commit (I had to adapt it because @houssine78 made the same fix in the meantime... but with pep8 errors ; and also the fix in invoice2data that was in my initial commit was already there...). 
I solve the github's question on SSH key and managed to push my commit this time ! We should now be OK.

**Comment by houssine78** [comment]
Hi @alexis-via  sorry for the pep8 error I get problems to commit cause didn't have sufficient access then I got a conflict so I've restarted the changes without checking the pep8.

**Pull request merged**
