### PR TITLE
[FIX] edi_oca: Adapt tests to changes on error messages

### PR DESCRIPTION
**Pull request by etobella**
@simahawk 
Solves #818
I had to apply the same patch on #814

Might be related to https://github.com/odoo/odoo/pull/135028 ?

### CODE REVIEW

**Comment by etobella** [comment]
@simahawk I tried to do this without removing the regex, but odoo is now using has_user_group, this checks if the call comes from a request and we are on debug mode. Obviously it is not the case on tests, so the result will never be accessible :sob:

**Review by bosd — APPROVED** [review]
Functional review. Tests are passing again. :+1

**Comment by etobella** [comment]
/ocabot merge patch

Merging as it is raising errors on current branch

**Comment by simahawk** [comment]
> has_user_group

you can still check the msg in the exception in theory. I'll have a look as I don't like we are not testing the right thing

**Comment by simahawk** [comment]
FTR fixed like this on v16 https://github.com/OCA/edi-framework/pull/5/commits/f1e6976f1bc510bbb014be53c343ebcf0f80a88f

**Pull request merged**
