### PR TITLE
10.0 Bugfix typo method name order response

### PR DESCRIPTION
**Pull request by lmarion-source**

### CODE REVIEW

**Comment by bealdav** [comment]
Hi @lmarion-source probably you have to rebase with oca 10.0. Thanks

**Comment by astirpe** [comment]
Looking at how the code was written, it seems to me that method `parse_xml_order_document()` returning the `parse_xml_order()` was made on purpose.
@lmarion-source What is the issue you are trying to fix?

**Review by astirpe — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]

**Comment by astirpe** [comment]
@lmarion-source you can merge the two PRS  #227 and #228 into one single PR.

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@astirpe Can we merge this one and #228 PLZ?

**Comment by lmignon** [comment]
Thank you @astirpe

**Pull request merged**
