### PR TITLE
business_document_import: Improve vat match

### PR DESCRIPTION
**Pull request by bosd**
Improve comments in the code.
Error message on tax type.
Fix vat matching. Previously the spaces where not stripped from the imported document. It was checked against the sanitized vat and didn't match.

### CODE REVIEW

**Comment by bosd** [comment]
@gbrito-erpopen Can you please review this one?
Maybe this fix can be merged soon, so it can be included in  #724

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@bosd Sure, I will rebase the 16.0 as soon as gets merged

**Comment by bosd** [comment]
@simahawk Can you review this one? 🙏

**Comment by bosd** [comment]
@bofiltd , @etobella Can you please review?

**Review by bofiltd — APPROVED** [review]
LGTM

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
