### PR TITLE
French Translation of account_invoice_import_simple_pdf

### PR DESCRIPTION
**Pull request by klodr**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please do the translation here: https://translation.odoo-community.org/projects/edi-14-0/edi-14-0-account_invoice_import_simple_pdf/

**Comment by klodr** [comment]
> Please do the translation here: https://translation.odoo-community.org/projects/edi-14-0/edi-14-0-account_invoice_import_simple_pdf/

Please read the commit before closing it. Since the 12th of april nobody as validated my transifex access or even reply to my emails.
This transifex thing is not working.

**Comment by pedrobaeza** [comment]
This has nothing to do with Transifex. It's weblate. Anyways, I don't see such explanation in the PR till now.

**Comment by simahawk** [comment]
@klodr thanks for your contrib but Transifex is not used since quite some time.
We use Weblate: please follow the link that Pedro provided.

TIP: next time don't hide such message in the commit -> is not relevant for the commit, is not prominent for reviewers :wink: 

image

**Comment by alexis-via** [comment]
I talked with @klodr following this PR. He told me that he created accounts both on transifex AND weblate, but none of his accounts have been validated so far. @sbidoul have you seen a request to approve an OCA weblate account for French language from klodr (Claude Perrin) ?

French translation is very limited on OCA modules and sometimes of poor quality on official modules. So it's very important that we don't demotivate new contributors on French translation ! It's not easy for a new translation contributor to understand the difference between transifex, weblate, follow the account approval process, etc. For example, I think a potential answer when such a PR arrives could be "OK, I merge this translation PR, but please use Weblate next time."

**Comment by sbidoul** [comment]
> have you seen a request to approve an OCA weblate account for French language from klodr (Claude Perrin) ?

Nope. But there is a `klodr` account on https://translation.odoo-community.org, with access to a bunch of languages, including French. @klodr let me know if you have difficulties accessing that. Also, if there are remaining references to Transifex on https://odoo-community.org, please let us know so we can fix them.

@alexis-via request for translations are processed weekly, assuming we receive them (lost emails is a thing, unfortunately).
If you have suggestions to improve the process I'm all ears as you know. But nope, don't translate on GitHub. Or if you do and there is a merge conflict, then I blindly reset the repo on weblate and ongoing translations are lost, as I have no time to resolve conflicts manually.

**Comment by alexis-via** [comment]
With my support, Claude has pushed his PO file for account_invoice_import_simple_pdf to OCA weblate. So it should arrive on github in the coming hours. Thanks for your help Stéphane.

**Comment by klodr** [comment]
Thanks all for following up on this matter. I had last 12th of  April requested access vie transbot@odoo-community.org to weblate. And again last on May. the 30. Never received an email from anybody. It's seems that I've been silently approved.
Great. Thanks a lot. Now we can work

**Comment by sbidoul** [comment]
@klodr I find no trace of your April 12th request. I found the task created from your May 30th message, and it was processed on June 8th. It's surprising you've not received the notification.

image

**Comment by klodr** [comment]
Nope never received this message 
Anyhow thanks / problem solved for me
Is there a way to extract 
1 a full repository / eg: oca/edi
2 in one language
3 in xliff 
4 in one click 
?  Or where can I find support ?

**Comment by sbidoul** [comment]
> Is there a way to extract...

I don't know if weblate supports that. The documentation is at https://docs.weblate.org/en/latest/user/basic.html - we currently run version 4.3.2.

>  Or where can I find support ?

For OCA-related support, contributors@odoo-community.org is probably your best bet.
I don't actually know if weblate has an official forum or something similar.

**Pull request closed without merging**
