### PR TITLE
[ADD] adds modules from v10, migrates factur-x modules to v11

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please only one module per PR, and there are some of them already migrated. Closing meanwhile.

**Comment by wpichler** [comment]
One thought about the "one module per PR" thing - i don't think that this is really a good idea - because many modules do depend on other modules - so you are not able to easy test such a PR - also runbot will fail on it. Wouldn't it be better to say "one PR for one module with its depends ?"

**Comment by pedrobaeza** [comment]
No, it's one module per PR. You start from the one without any inter-dependencies, and then you can create consecutive PRs with the following modules. It's very easy to fulfill dependencies between PRs adding a temporary commit in the dependent PRs with the branch from the other PR put in oca_repositories.txt, and thus having green runbot/Travis meanwhile the base one is merged. Other contributors just wait to push the other ones until the base one is merged.

Why doing this way? Simply for easing and speeding up the reviewing process, although it seems to be the contrary at the beginning. It's far more difficult to review a PR with a bunch of modules than only one. And also a blocking comment on the final dependent module will block the entire PR (while base modules can be correct) doing on a batch mode.

**Comment by wpichler** [comment]
Ok - i got the point - thanks for explaining this...

**Comment by pedrobaeza** [comment]
Let me know if you need assistance in the process. Check also https://github.com/OCA/edi/issues/29 for tracking the progress of the migration of the modules of the repository.

**Comment by wpichler** [comment]
Ok - maybe we will need some assistence - we do currently port all edi ubl modules to version 11. And we will add some more modules - to be able to handle the transfer of generated pdf / xml / whatever files with a transfer base module - and then some provider depended specific transfer modules (holodeck AS4 for example)

**Pull request closed without merging**
