### PR TITLE
[8.0] [FEATURE] Store templates in db

### PR DESCRIPTION
**Pull request by rconjour**
Store templates for invoice2data in the database instead of file storage as discussed in https://github.com/OCA/edi/issues/117#issuecomment-515868626

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Let me close and reopen this PR to force a new build attempt by Travis as it broke because of networking issues.

**Comment by StefanRijnhart** [comment]
Please add a requirements.txt file for invoice2data. See for example https://github.com/OCA/partner-contact/blob/8.0/requirements.txt

**Comment by StefanRijnhart** [comment]
```
======== Testing test_flake8 ========

account_invoice_import_invoice2data/models/invoice2data_template.py:18:5: F401 'invoice2data.main.logger as loggeri2data' imported but unused

account_invoice_import_invoice2data/tests/test_invoice2data_template.py:60:5: E303 too many blank lines (2)
```

**Comment by bealdav** [comment]
I don't know if you rebased your PR with 8.0, but we clean it some days ago. It worth

**Pull request closed without merging**
