### PR TITLE
[12.0] add missing factur-x dependency

### PR DESCRIPTION
**Pull request by sbidoul**
Let's see if travis is happy with this

### CODE REVIEW

**Comment by sbidoul** [comment]
Travis is red saying: `Modules "Account e-invoice Generate" and "Import Vendor Bills From XML" are incompatible.`.

**Comment by sbidoul** [comment]
I guess we need to uninstall Odoo's `account_facturx`, not sure if we've ever had to do that with MQT.

**Comment by bealdav** [comment]
Here is what I have done in l10n-fr https://github.com/OCA/l10n-france/blob/12.0/.travis.yml#L26

As said here https://github.com/OCA/l10n-france/pull/214

> Maybe remove auto_install of account_facturx module in OCB

and then only test with OCB ...

Maybe you have a better idea ?

**Comment by sbidoul** [comment]
@bealdav yes I made a commit to get Odoo's `account_facturx` out of the way.

Now there seem to be an error in demo data: `account_invoice_import_facturx.fr_vat_purchase_20`, trying to fix it.

**Comment by sbidoul** [comment]
Hm, this 12.0 branch is in a sad state... now there is a bug somewhere in `embed_xml_in_pdf`... 

@alexis-via, help!

**Comment by astirpe** [comment]
@sbidoul the error you mentioned should be fixed by https://github.com/OCA/edi/pull/195

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
