### PR TITLE
[14.0][MIG] account_invoice_import_ubl

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@alexis-via Can you see if my feedback in #267 can be considered?

**Comment by dsolanki-initos** [comment]
Hello @alexis-via can you please resolve the failed checks?

**Comment by fshah-initos** [comment]
@alexis-via  It would be great if you can resolve the failed checks

**Comment by StefanRijnhart** [comment]
There is a superseding PR here: https://github.com/OCA/edi/pull/390 based on the 13.0 port (https://github.com/OCA/edi/pull/267)

The only difference, as far as I can tell, is that it has XML linting applied on the UBL XML files, and demo_data.xml has gone through a round trip of having its indentation level modified in the 13.0 port and restored in the 14.0 port.

@alexis-via do you feel that the UBL XML files should be left alone by the XML linter? We could consider having them ignored in that case.

**Comment by alexis-via** [comment]
@StefanRijnhart I prefer if the demo/test XML files are left unchanged (but it's not a big deal). I don't know how to make them ignored by pre-commit/flake8 (and I need that for other modules too). I remember you mentioned the solution in another comment... but I can't find it at the moment.

**Pull request closed without merging**
