### PR TITLE
[ADD] PEPPOL UBL-DT-07: filename attribute to binary attachment

### PR DESCRIPTION
**Pull request by thomaspaulb**
Obligatory in [PEPPOL UBL-DT-07](https://docs.peppol.eu/poacc/billing/3.0/rules/UBL-DT-07).

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@StefanRijnhart @bealdav @gjotten

**Review by gjotten — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@bealdav Please merge

**Comment by thomaspaulb** [comment]
@etobella Can we still cancel this? I had to push a fixup commit still...

**Pull request closed without merging**
