### PR TITLE
[14.0] [mig] base_facturx

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
Supresed by #256

**Review by rconjour — APPROVED** [review]

**Review by dsolanki-initos — APPROVED** [review]

**Comment by fshah-initos** [comment]
It would be great if the maintainers could merge the PR.

**Comment by dreispt** [comment]
Needs a rebase to fix conflicts. Thanks!

**Comment by gurneyalex** [comment]
#256 was merged

**Pull request closed without merging**
