### PR TITLE
[FIX] invoice2data Fallback to tesseract

### PR DESCRIPTION
**Pull request by bosd**
The invoice2data module usage instructions include:

> If you want the invoice2data library to fallback on OCR if the PDF doesn't contain text (only a very small minority of PDF invoices are image-based and require OCR), you should also install [Imagemagick](http://www.imagemagick.org/)

However, it does not fallback if pdftotext fails.
This code fixes that..

### CODE REVIEW

**Comment by bosd** [comment]
@alexis-via Can you review? :pray:

**Comment by bosd** [comment]
@MTantin Would you like to review this one as well?

**Comment by bosd** [comment]
@i-vyshnevska can you please review

**Review by bofiltd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@oca/edi-maintainers Can this one be re-opened. Maybe this is not the best implementation. But the functionality is really a great addition.

**Comment by bosd** [comment]
@etobella Could you please reopen this one?

**Comment by etobella** [comment]
I cannot reopen it, as the branch has been force pushed or recreated :cry: 
@etobella

**Pull request closed without merging**
