### PR TITLE
[BUGFIX] Fix method name in purchase order

### PR DESCRIPTION
**Pull request by lmarion-source**

### CODE REVIEW

**Comment by astirpe** [comment]
Looking at how the code was written, it seems to me that method `parse_xml_quote()` returning the `parse_xml_order()` was made on purpose.
@lmarion-source What is the issue you are trying to fix?

**Comment by astirpe** [comment]
Sorry, my bad. Forget my previous comment.

**Review by astirpe — APPROVED** [review]
Fix looks good to me.

**Review by rousseldenis — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Pull request merged**
