### PR TITLE
[14.0] New module account_invoice_import_simple_pdf (invoice2data alternative)

### PR DESCRIPTION
**Pull request by alexis-via**
This new module is an improved alternative to the module account_invoice_import_invoice2data. Refer to README for more information.

### CODE REVIEW

**Comment by alexis-via** [comment]
Here is a screencast which will show you how to configure and use the module: https://www.youtube.com/watch?v=edsEuXVyEYE

**Comment by gdgellatly** [comment]
Hi @alexis-via

I installed this to give it a test. Some comments from that process.

1. python3-fitz or python3-mupdf is not available in stable Debian. To install you must do so by `sudo apt install libmupdf-dev mupdf-tools mupdf` . Weirdly it wouldn't work for me until I put in the dev headers. Then you can pip install PyMuPDF. Now whether this actually works I have not tested yet.

2. The module itself won't install. I simply cannot believe it is the modules fault but this is what happens. It creates the columns for  `simple_pdf_date_separator` and the previous one. It then attempts to do the defaults before adding rest of columns. Now I can only assume here it is because of the selection function, and the default. If I comment out all the functional selection fields default arguments , the module installs fine.

3. I am not sure this module and invoice2data need to be mutually exclusive. I think it is worth looking at how Odoo handles multiple import parsers for the same invoice file type. In fact, I think account_invoice_import can successfully use it. I have been using with v12 and invoice2data for some time, falling back to OCR. Essentially iterates over a list until it is returned an invoice. That said I am not sure I will still need invoice2data, just saying they can coexist.

**Comment by alexis-via** [comment]
@gdgellatly Thanks for your feedback !
1. As my laptop runs on Ubuntu 20.04 LTS where the package python3-fitz, I discovered the difficulty to install pymupdf later. Hopefully, Debian 11 will be release in 3 days (cf https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html) and the package python3-fitz is available on debian 11 cf https://packages.debian.org/bullseye/python3-fitz
2. Very very strange. I don't have such a problem and I received other feedbacks that didn't report such a problem.
3. It's true that, from a technical point of view, account_invoice_import_invoice2data could cohabit with account_invoice_import_simple_pdf. But, for me, it doesn't make sense to use both and account_invoice_import_simple_pdf is much better. So I don't plan to maintain account_invoice_import_invoice2data any more.

**Comment by alexis-via** [comment]
Debian 11 has been released https://bits.debian.org/2021/08/bullseye-released.html
Will make this module easier to install for Debian users!
BTW, while backporting to v12, I came across a strange thing:
this lib is called PyMuPDF (https://pypi.org/project/PyMuPDF/) but when we import it we run "import fitz".
On v14, in the manifest, I write :
```
"external_dependencies": {"python": ["PyMuPDF", "..."]}
```
but it doesn't work in v12 (says the lib is not found). In v12, I solved the pb by writing:
```
"external_dependencies": {"python": ["fitz", "..."]}
```
Is it normal ?

**Comment by alexis-via** [comment]
@gdgellatly I managed to reproduce the bug of your point 2 !
When I install the module account_invoice_import_simple_pdf via the "Applications" menu of the web interface, it works well
But, when I install the module via the command line (-i account_invoice_import_simple_pdf) or by adding the module to the 'depends' key of the manifest of another module, it fails:

```
2021-08-23 13:31:05,820 25332 INFO o4_test1 odoo.modules.registry: module account_invoice_import_simple_pdf: creating or updating database tables 
2021-08-23 13:31:05,913 25332 ERROR o4_test1 odoo.sql_db: bad query: SELECT "res_partner"."id" as "id", "res_partner"."name" as "name", "res_partner"."display_name" as "display_name", "res_partner"."date" as "date", "res_partner"."title" as "title", "res_partner"."parent_id" as "parent_id", "res_partner"."lang" as "lang", "res_partner"."tz" as "tz", "res_partner"."vat" as "vat", "res_partner"."website" as "website", "res_partner"."comment" as "comment", "res_partner"."credit_limit" as "credit_limit", "res_partner"."active" as "active", "res_partner"."employee" as "employee", "res_partner"."function" as "function", "res_partner"."type" as "type", "res_partner"."street" as "street", "res_partner"."street2" as "street2", "res_partner"."zip" as "zip", "res_partner"."city" as "city", "res_partner"."state_id" as "state_id", "res_partner"."country_id" as "country_id", "res_partner"."partner_latitude" as "partner_latitude", "res_partner"."partner_longitude" as "partner_longitude", "res_partner"."mobile" as "mobile", "res_partner"."is_company" as "is_company", "res_partner"."industry_id" as "industry_id", "res_partner"."company_id" as "company_id", "res_partner"."color" as "color", "res_partner"."partner_share" as "partner_share", "res_partner"."commercial_partner_id" as "commercial_partner_id", "res_partner"."commercial_company_name" as "commercial_company_name", "res_partner"."company_name" as "company_name", "res_partner"."ref" as "ref", "res_partner"."email" as "email", "res_partner"."phone" as "phone", "res_partner"."user_id" as "user_id", "res_partner"."signup_token" as "signup_token", "res_partner"."signup_type" as "signup_type", "res_partner"."signup_expiration" as "signup_expiration", "res_partner"."calendar_last_notif_ack" as "calendar_last_notif_ack", "res_partner"."department_id" as "department_id", "res_partner"."partner_gid" as "partner_gid", "res_partner"."additional_info" as "additional_info", "res_partner"."debit_limit" as "debit_limit", "res_partner"."last_time_entries_checked" as "last_time_entries_checked", "res_partner"."invoice_warn_msg" as "invoice_warn_msg", "res_partner"."supplier_rank" as "supplier_rank", "res_partner"."customer_rank" as "customer_rank", "res_partner"."team_id" as "team_id", "res_partner"."picking_warn_msg" as "picking_warn_msg", "res_partner"."invoice_warn" as "invoice_warn", "res_partner"."tax_receipt_option" as "tax_receipt_option", "res_partner"."donor_rank" as "donor_rank", "res_partner"."celebrant" as "celebrant", "res_partner"."purchase_warn_msg" as "purchase_warn_msg", "res_partner"."picking_warn" as "picking_warn", "res_partner"."purchase_warn" as "purchase_warn", "res_partner"."sale_warn_msg" as "sale_warn_msg", "res_partner"."siren" as "siren", "res_partner"."nic" as "nic", "res_partner"."siret" as "siret", "res_partner"."company_registry" as "company_registry", "res_partner"."sale_warn" as "sale_warn", "res_partner"."fr_das2_type" as "fr_das2_type", "res_partner"."fr_das2_job" as "fr_das2_job", "res_partner"."intrastat_fiscal_representative_id" as "intrastat_fiscal_representative_id", "res_partner"."email_normalized" as "email_normalized", "res_partner"."message_bounce" as "message_bounce", "res_partner"."message_main_attachment_id" as "message_main_attachment_id", "res_partner"."phone_sanitized" as "phone_sanitized", "res_partner"."simple_pdf_keyword" as "simple_pdf_keyword", "res_partner"."simple_pdf_date_format" as "simple_pdf_date_format", "res_partner"."simple_pdf_date_separator" as "simple_pdf_date_separator", "res_partner"."simple_pdf_decimal_separator" as "simple_pdf_decimal_separator", "res_partner"."simple_pdf_thousand_separator" as "simple_pdf_thousand_separator", "res_partner"."simple_pdf_pages" as "simple_pdf_pages", "res_partner"."simple_pdf_currency_id" as "simple_pdf_currency_id", "res_partner"."simple_pdf_test_filename" as "simple_pdf_test_filename", "res_partner"."simple_pdf_test_raw_text" as "simple_pdf_test_raw_text", "res_partner"."simple_pdf_test_results" as "simple_pdf_test_results", "res_partner"."create_uid" as "create_uid", "res_partner"."create_date" as "create_date", "res_partner"."write_uid" as "write_uid", "res_partner"."write_date" as "write_date" FROM "res_partner" WHERE "res_partner".id IN (2)
ERROR: column res_partner.simple_pdf_date_separator does not exist
LINE 1: ...ple_pdf_date_format" as "simple_pdf_date_format", "res_partn...
```

Very very strange !
But at least, I know have a scenario to reproduce the bug.

**Comment by alexis-via** [comment]
I've been asked about the possibility to deploy this module in Odoo SH, but I don't have any experience with Odoo SH. Has anyone successfully tried this module on Odoo SH ? The difficulty may be linked to the use of PyMuPDF, which is a python binding on the tool MuPDF...

**Comment by gdgellatly** [comment]
@alexis-via I've started looking at this. I'd like to decouple the invoice parser from needing specific fields knowledge to ease extensibility. e..g If I want to add Operating Unit, or payment ref, or origin. What do you think? Partial diff below of the idea. I know the base is still somewhat tightly coupled but doesn't always need to be.

Also `comma` not `coma`, quite different pauses :)

```
@@ -295,6 +295,15 @@ class AccountInvoiceImportSimplePdfFields(models.Model):
         else:
             parsed_inv["failed_fields"].append(self.name)
 
+    def _get_date_due(self, *args):
+        return self._get_date(*args)
+
+    def _get_date_start(self, *args):
+        return self._get_date(*args)
+
+    def _get_date_end(self, *args):
+        return self._get_date(*args)
+
```

```
--- a/account_invoice_import_simple_pdf/wizard/account_invoice_import.py
+++ b/account_invoice_import_simple_pdf/wizard/account_invoice_import.py
@@ -162,16 +162,10 @@ class AccountInvoiceImport(models.TransientModel):
         # Check field config
         for field in partner.simple_pdf_field_ids:
             logger.debug("Working on field %s", field.name)
-            if field.name.startswith("date"):
-                field._get_date(parsed_inv, raw_text, partner_config, test_info)
-            elif field.name.startswith("amount_"):
-                field._get_amount(parsed_inv, raw_text, partner_config, test_info)
-            elif field.name == "invoice_number":
-                field._get_invoice_number(
-                    parsed_inv, raw_text, partner_config, test_info
-                )
-            elif field.name == "description":
-                field._get_description(parsed_inv, raw_text, partner_config, test_info)
+            try:
+                getattr(field, "_get_%s" % field.name)(parsed_inv, raw_text, partner_config, test_info)
+            except AttributeError:
+                logger.warning("Failed to find parse function for field %s", field.name)
 
         failed_fields = parsed_inv.pop("failed_fields")
```

**Comment by legalsylvain** [comment]
hi @alexis-via. Thanks for sharing this module. 
looking forward to the presentation at the OCA Days ! (https://odoo-community.org/event/oca-days-2021-online-2021-10-28-2021-10-29-128/track/new-module-to-import-pdf-supplier-invoices-86)

Could you rebase to fix conflict on requirement ? 

thanks.

**Comment by alexis-via** [comment]
@gdgellatly I renamed coma to comma!

**Comment by alexis-via** [comment]
@gdgellatly and I implemented your suggestion with getattr

**Review by bealdav — APPROVED** [review]
Tested and works nicely, no code review

**Comment by PierrickBrun** [comment]
Tested OK
No code review

Does not seem to work if the partner's VAT number is not the first one in the document

**Review by mourad-ehm — APPROVED** [review]
Tested in prod. Thanks @alexis-via for this module

**Pull request merged**
