### PR TITLE
[12.0][BKP] edi_oca: Backport from 14.0

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Supersedes https://github.com/OCA/edi/pull/802 and https://github.com/OCA/edi/pull/860.

### CODE REVIEW

**Comment by QuocDuong1306** [comment]
Hello @MiquelRForgeFlow , thanks for your effort!, could you have a look at `tests` (it's still red now)?

**Comment by MiquelRForgeFlow** [comment]
@QuocDuong1306 if you can help me solve those errors, it would be nice :)

**Comment by QuocDuong1306** [comment]
Thank @MiquelRForgeFlow, Sure, I'm going to have a look and prepare a PR for your branch

**Comment by QuocDuong1306** [comment]
Hello @MiquelRForgeFlow ,

I have done the fix 1 on this: https://github.com/OCA/queue/pull/617 (merged)

Could you pick my commit about `account_invoice_facturx`: https://github.com/OCA/edi/pull/908/commits/b4e0c6b27ad1780017b00266e97b19c802344139
image
 - The implementation of [account_invoice_facturx](https://github.com/OCA/edi/blob/d1b78c754c06e53bfbc093f64c2c7ff443fa686a/account_invoice_facturx/models/ir_actions_report.py#L12) was override by [account_facturx](https://github.com/odoo/odoo/blob/ba1ba88874e2ae9716e59ec199eb739d58c3f771/addons/account_facturx/models/ir_actions_report.py#L14)
 - So it causes errors on tests and maybe makes the `account_invoice_facturx` module useless...

**Comment by MiquelRForgeFlow** [comment]
@simahawk could you merge?

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by simahawk** [comment]
Can we merge w/ `patch` or you are relying on any upgrade step for specific versions?
Otherwise you have to bump other modules versions manually (the ones not migrated I mean).
Sorry, I have no time to review everything here :sweat_smile:

**Comment by MiquelRForgeFlow** [comment]
Yeah, you can merge w/ `patch`.

**Pull request merged**
