### PR TITLE
[14.0][FIX] edi: remove span inside anchor to fix exchange record navigation

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
FW of https://github.com/OCA/edi/pull/523

CC @LoisRForgeFlow @etobella

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Review by simahawk — APPROVED** [review]
LG but pls pay attention to https://github.com/OCA/edi/pull/523#issuecomment-1032583672 next time :pray:

**Comment by etobella** [comment]
@JordiMForgeFlow Can you change commit message following @simahawk comments and cherry-pick it to 15?

Thanks!

**Comment by JordiMForgeFlow** [comment]
@etobella @simahawk Done in #533, sorry for the commit message 🙏🏼 :)

**Review by etobella — APPROVED** [review]

**Pull request merged**
